steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.signal-job
      - -t
      - ${_IMAGE}
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_IMAGE}
images:
  - ${_IMAGE}
substitutions:
  _IMAGE: unused.invalid/venusrealm-signal-agent:unset
