import Link from "next/link";
import { ContentGrid } from "@/components/content-grid";
import { Icon, type IconName } from "@/components/icon";
import { getContent, getSignalSnapshot } from "@/lib/api";
import { configuredLinks } from "@/lib/site-config";

export const revalidate = 300;

export default async function HomePage() {
  const [content, signals] = await Promise.all([
    getContent(undefined, 12), getSignalSnapshot()
  ]);
  const publishedBlogs = content.filter((item) => ["BLOG", "AI_BLOG", "ANALYSIS", "EDUCATION", "ADVISORY"].includes(item.content_type)).slice(0, 6);
  const astrology = content.filter((item) => `${item.title} ${item.excerpt || ""} ${item.category_title || ""}`.toLowerCase().includes("astrolog"));
  const latest = publishedBlogs[0];
  const signal = signals[0];
  const links = configuredLinks();
  const offers: { icon: IconName; title: string; text: string; href: string }[] = [
    { icon: "gold", title: "Gold Signals", text: "Structured XAUUSD levels with entries, invalidation and risk context.", href: "/signals" },
    { icon: "chart", title: "Market Analysis", text: "Clear technical and macro research designed for considered decisions.", href: "/category/analysis-department" },
    { icon: "moon", title: "Financial Astrology", text: "Educational exploration of planetary cycles and market timing.", href: "/astrology" },
    { icon: "book", title: "Learning", text: "Practical market education grounded in discipline and risk control.", href: "/category/market-education" },
    { icon: "send", title: "Telegram Alerts", text: "Fast channel delivery when a verified public alert is available.", href: links.telegram || "/contact" },
    { icon: "brain", title: "AI Research", text: "AI-assisted synthesis with explicit risk framing and editorial review.", href: "/blog" }
  ];
  const updateTime = signal?.updated_at || signal?.published_at || signal?.signal_time || latest?.published_at || latest?.created_at;
  return <>
    <section className="hero">
      <div className="hero-copy"><span className="eyebrow"><span />GOLD INTELLIGENCE, BUILT FOR CLARITY</span><h1>Read the gold market with <em>calm conviction.</em></h1><p>VenusRealm brings XAUUSD signals, market structure, financial astrology and AI-assisted research into one disciplined, educational view.</p><div className="hero-actions"><Link className="button button-gold" href="/signals">View Gold Signals <Icon name="arrow" size={18} /></Link>{links.telegram && <a className="button button-ghost" href={links.telegram} rel="noreferrer" target="_blank"><Icon name="send" size={18} />Join Telegram</a>}</div><div className="trust-chips"><span><Icon name="brain" size={16} />AI-assisted research</span><span><Icon name="shield" size={16} />Risk-first analysis</span><span><Icon name="book" size={16} />Educational content</span></div></div>
      <div className="hero-visual" aria-label="Abstract VenusRealm gold market orbit"><div className="orbital-ring ring-one"/><div className="orbital-ring ring-two"/><div className="gold-core"><Icon name="gold" size={40} /><b>XAUUSD</b><span>market intelligence</span></div><div className="orbit-note note-one"><span>Structure</span><b>Before signal</b></div><div className="orbit-note note-two"><span>Risk</span><b>Before reward</b></div></div>
    </section>

    <section className="market-snapshot" aria-labelledby="snapshot-title"><div className="section-heading compact-heading"><div><span className="eyebrow">MARKET SNAPSHOT</span><h2 id="snapshot-title">The desk, at a glance.</h2></div><span className="data-note"><span className="status-dot" />Cached public data</span></div><div className="snapshot-grid"><Snapshot label="XAUUSD status" value={signal?.signal_type || "No verified signal"} detail={signal?.symbol || "Awaiting a published market row"} /><Snapshot label="Latest published signal" value={signal?.price != null ? String(signal.price) : "Not available"} detail={signal ? "See the signal desk for risk levels" : "No public signal is active"} /><Snapshot label="Latest analysis" value={latest?.title || "Research unavailable"} detail={latest?.category_title || "Published editorial research"} href={latest ? `/blog/${latest.slug}` : "/blog"} /><Snapshot label="Last public update" value={updateTime ? new Intl.DateTimeFormat("en", { day: "numeric", month: "short", hour: "2-digit", minute: "2-digit" }).format(new Date(updateTime)) : "Not available"} detail="Times reflect published public data" /></div></section>

    <section aria-labelledby="offers-title"><div className="section-heading"><div><span className="eyebrow">WHAT VENUSREALM OFFERS</span><h2 id="offers-title">One research layer. Six focused tools.</h2></div><p>Built to help readers separate market context from market noise.</p></div><div className="offer-grid">{offers.map((offer) => <Link href={offer.href} className="offer-card" key={offer.title}><span className="icon-box"><Icon name={offer.icon} /></span><h3>{offer.title}</h3><p>{offer.text}</p><span className="text-link">Explore <Icon name="arrow" size={16} /></span></Link>)}</div></section>

    <section className="dark-section" aria-labelledby="signals-title"><div className="section-heading"><div><span className="eyebrow">LATEST GOLD SIGNALS</span><h2 id="signals-title">Defined levels. Visible risk.</h2></div><Link className="text-link" href="/signals">Open signal desk <Icon name="arrow" size={16} /></Link></div>{signals.length ? <div className="signal-cards">{signals.slice(0, 3).map((item, index) => <div className="signal-card" key={item.id || index}><div><span>{item.symbol || "XAUUSD"}</span><b>{item.signal_type || "WATCH"}</b></div><dl><div><dt>Timeframe</dt><dd>{item.timeframe || "—"}</dd></div><div><dt>Entry</dt><dd>{item.price ?? "—"}</dd></div><div><dt>Stop loss</dt><dd>{item.stop_loss ?? "—"}</dd></div><div><dt>Targets</dt><dd>{[item.target_1,item.target_2,item.target_3].filter((value) => value != null).join(" · ") || "—"}</dd></div></dl></div>)}</div> : <div className="empty-state empty-dark"><Icon name="clock" /><div><h3>No verified signal is currently published</h3><p>The desk will display real levels here when a public signal is available. No placeholder prices are shown.</p></div></div>}</section>

    <section aria-labelledby="analysis-title"><div className="section-heading"><div><span className="eyebrow">LATEST MARKET ANALYSIS</span><h2 id="analysis-title">Research for the next considered move.</h2></div><Link className="text-link" href="/blog">Browse all research <Icon name="arrow" size={16} /></Link></div><ContentGrid items={publishedBlogs} /></section>

    <section className="astrology-section" aria-labelledby="astrology-title"><div className="astrology-copy"><span className="eyebrow">FINANCIAL ASTROLOGY</span><h2 id="astrology-title">A wider lens on market timing.</h2><p>VenusRealm treats astrology as an educational timing framework—not a standalone trading signal. Planetary cycles are considered alongside market data, structure and risk.</p><Link className="button button-light" href="/astrology">Explore the methodology <Icon name="arrow" size={18} /></Link></div><div className="astro-panel"><Icon name="moon" size={32} /><span>Planetary market timing</span><strong>{astrology.length ? `${astrology.length} published insight${astrology.length === 1 ? "" : "s"}` : "Upcoming research desk"}</strong><p>{astrology.length ? astrology[0].title : "No astrology article has been published yet. New material will appear only after editorial review."}</p></div></section>

    <section id="how-it-works" aria-labelledby="process-title"><div className="section-heading centered-heading"><div><span className="eyebrow">HOW IT WORKS</span><h2 id="process-title">From market input to public insight.</h2></div></div><ol className="process-grid"><Process number="01" icon="globe" title="Market data" text="Published market inputs and price context form the factual base."/><Process number="02" icon="brain" title="AI + astrology analysis" text="Research tools synthesize structure, narrative and timing frameworks."/><Process number="03" icon="shield" title="Risk and compliance review" text="Claims, levels and language are checked through a risk-first lens."/><Process number="04" icon="send" title="Publish and alert" text="Approved public content is released to the site and configured channels."/></ol></section>

    <section className="why-section" aria-labelledby="why-title"><div><span className="eyebrow">WHY VENUSREALM</span><h2 id="why-title">Designed for disciplined readers, not impulsive clicks.</h2><p>Every section prioritizes context, explicit uncertainty and educational value.</p></div><div className="principle-grid">{["Risk-first approach","Transparent educational analysis","Fast configured alerts","Multi-channel updates","Structured editorial content","Human approval where applicable"].map((item) => <span key={item}><Icon name="check" size={17} />{item}</span>)}</div></section>

    <section id="results" className="results-section" aria-labelledby="results-title"><div><span className="eyebrow">VERIFIED RESULTS</span><h2 id="results-title">Proof should be documented, not promised.</h2><p>No verified performance dataset is currently available through the public API. VenusRealm will not display invented win rates, profits or testimonials.</p></div><div className="empty-proof"><Icon name="target" size={28} /><strong>Awaiting verified public records</strong><span>Results will appear only with source data and clear methodology.</span></div></section>

    <section className="video-section" aria-labelledby="video-title"><div><span className="eyebrow">VIDEO & YOUTUBE</span><h2 id="video-title">Watch the research process.</h2><p>{links.video || links.youtube ? "Open the configured VenusRealm video channel for published market education." : "No public video channel is configured for this preview. No placeholder videos are loaded."}</p></div>{(links.video || links.youtube) && <a className="button button-dark" href={links.video || links.youtube} rel="noreferrer" target="_blank">Open YouTube <Icon name="arrow" size={18} /></a>}</section>

    <section id="faq" aria-labelledby="faq-title"><div className="section-heading"><div><span className="eyebrow">FAQ</span><h2 id="faq-title">Clear answers before you begin.</h2></div></div><div className="faq-list"><Faq question="Are signals financial advice?">No. Signals and analysis are educational information and do not account for your circumstances. You remain responsible for every financial decision.</Faq><Faq question="How are signals created?">Public signals may combine market data, structured analysis and automated research, followed by the approval controls applicable to the publishing workflow.</Faq><Faq question="Is astrology used alone?">No. Astrology is presented as an educational timing lens and should never replace market structure, risk management or independent judgment.</Faq><Faq question="Where are alerts delivered?">Alerts appear on the public signal desk. Telegram or WhatsApp links are shown only when those public channels are configured.</Faq><Faq question="What are the risks?">Gold and leveraged markets can move quickly. Losses may exceed expectations, past results do not predict future outcomes, and no signal guarantees a result.</Faq></div></section>

    <section className="final-cta"><div><span className="eyebrow">READ THE MARKET DIFFERENTLY</span><h2>Clarity for gold. Discipline for every decision.</h2></div><div className="cta-actions"><Link className="button button-gold" href="/signals">View Signals</Link>{links.telegram && <a className="button button-light" href={links.telegram} rel="noreferrer" target="_blank">Join Telegram</a>}<Link className="button button-ghost" href="/blog">Read Latest Analysis</Link></div></section>
  </>;
}

function Snapshot({ label, value, detail, href }: { label: string; value: string; detail: string; href?: string }) { const content = <><span>{label}</span><strong>{value}</strong><small>{detail}</small></>; return href ? <Link className="snapshot-card" href={href}>{content}</Link> : <div className="snapshot-card">{content}</div>; }
function Process({ number, icon, title, text }: { number: string; icon: IconName; title: string; text: string }) { return <li><span className="process-number">{number}</span><span className="icon-box"><Icon name={icon}/></span><h3>{title}</h3><p>{text}</p></li>; }
function Faq({ question, children }: { question: string; children: React.ReactNode }) { return <details><summary>{question}<span aria-hidden="true">+</span></summary><p>{children}</p></details>; }
