import Image from "next/image";
import Link from "next/link";
import { FaqItem, InsightCard, ResearchToolCard, SnapshotItem } from "@/components/homepage-sections";
import { ContentGrid } from "@/components/content-grid";
import { Icon, type IconName } from "@/components/icon";
import { getContent, getResultSnapshot, getSignalSnapshot } from "@/lib/api";
import { configuredLinks } from "@/lib/site-config";

export const revalidate = 300;

const tools: { icon: IconName; title: string; text: string; href: string }[] = [
  { icon: "gold", title: "Gold signals", text: "Structured XAUUSD context with member-only protected trade levels.", href: "/signals" },
  { icon: "chart", title: "Market analysis", text: "Technical and macro research built for considered decisions—not reaction.", href: "/category/analysis-department" },
  { icon: "moon", title: "Financial astrology", text: "An educational exploration of planetary cycles and market timing.", href: "/astrology" },
  { icon: "book", title: "Market learning", text: "Practical education grounded in process, discipline and risk control.", href: "/category/market-education" },
  { icon: "brain", title: "AI research", text: "AI-assisted synthesis with explicit risk framing and editorial review.", href: "/blog" },
];

const deliverables = [
  ["01", "Signal desk", "A clear public teaser layer plus protected member detail when access is verified."],
  ["02", "Research briefs", "Structured XAUUSD analysis that separates data, interpretation and uncertainty."],
  ["03", "Risk framework", "Invalidation, uncertainty and educational framing remain visible throughout the experience."],
  ["04", "Verified results", "Only compliance-reviewed public records are eligible for publication."],
  ["05", "Alert routing", "Configured channels can project approved public updates without becoming the source of truth."],
  ["06", "Member workflow", "Secure account, verification and payment-review flows remain distinct from public content."],
];

const audiences = [
  ["Discretionary gold traders", "Problem", "Too much noise around XAUUSD creates impulsive decisions.", "Approach", "Use structured context, explicit risk and a defined research workflow.", "Output", "A calmer decision framework before any trade is considered."],
  ["Research-driven members", "Problem", "Signals without methodology are difficult to evaluate.", "Approach", "Pair public education with protected member detail and transparent access controls.", "Output", "Clear separation between public context and actionable member information."],
  ["Macro + technical readers", "Problem", "Single-factor market narratives miss important context.", "Approach", "Combine technical structure, macro context and timing observations without overclaiming.", "Output", "A broader research lens with disciplined uncertainty."],
];

const modules = [
  ["Signal intelligence", "Public teaser status, protected member details and explicit access boundaries.", "/signals"],
  ["Market research", "Editorial XAUUSD analysis, education and published desk commentary.", "/blog"],
  ["Evidence layer", "Verified public results with privacy redaction and compliance-safe reporting.", "/results"],
  ["Timing research", "Financial astrology framed strictly as supplementary educational context.", "/astrology"],
];

export default async function HomePage() {
  const [content, signals, results] = await Promise.all([getContent(undefined, 12), getSignalSnapshot(), getResultSnapshot()]);
  const publishedBlogs = content.filter((item) => ["BLOG", "AI_BLOG", "ANALYSIS", "EDUCATION", "ADVISORY"].includes(item.content_type)).slice(0, 6);
  const astrology = content.filter((item) => `${item.title} ${item.excerpt || ""} ${item.category_title || ""}`.toLowerCase().includes("astrolog"));
  const latest = publishedBlogs[0];
  const signal = signals[0];
  const links = configuredLinks();
  const researchTools = links.telegram ? [...tools, { icon: "send" as IconName, title: "Telegram alerts", text: "Fast channel delivery when a verified public alert is available.", href: links.telegram }] : tools;
  const updateTime = signal?.updated_at || signal?.published_at || signal?.signal_time || latest?.published_at || latest?.created_at;

  return <div className="home-page">
    <section className="home-hero">
      <Image className="home-hero-art" src="/images/home/venusrealm-gold-desk-hero.png" alt="Gold bars and market charts inside a premium commodities research desk" fill priority sizes="(max-width: 760px) 100vw, 1240px" />
      <span className="home-hero-shade" aria-hidden="true" />
      <div className="home-hero-copy"><span className="eyebrow"><span />Independent gold intelligence</span><h1>Read gold with <em>clarity.</em><br />Act with discipline.</h1><p>VenusRealm brings XAUUSD signals, market structure, financial astrology and AI-assisted research into one calm, risk-first editorial desk.</p><div className="hero-actions"><Link className="button button-gold" href="/signals">Enter the signal desk <Icon name="arrow" size={18} /></Link><Link className="button home-button-outline" href="/blog">Read latest research</Link></div><div className="home-hero-proof" aria-label="Research principles"><span><Icon name="shield" size={15} />Risk before reward</span><span><Icon name="brain" size={15} />AI-assisted, editorially reviewed</span><span><Icon name="book" size={15} />Education, not advice</span></div></div>
      <aside className="terminal-panel" aria-label="VenusRealm research desk principles"><div className="terminal-topline"><span><i /> Research desk</span><small>Public intelligence</small></div><div className="terminal-market"><div><small>Primary market</small><strong>XAUUSD</strong></div><span className="terminal-status">Risk-first</span></div><div className="terminal-chart" aria-hidden="true"><span className="chart-line" /><span className="chart-marker marker-a" /><span className="chart-marker marker-b" /></div><div className="terminal-principles"><InsightCard index="01" label="Structure" value="Before signal" /><InsightCard index="02" label="Context" value="Before conviction" /><InsightCard index="03" label="Risk" value="Before reward" /></div><p>Every public insight moves through a controlled research and publishing workflow.</p></aside>
    </section>

    <section className="desk-strip" aria-labelledby="snapshot-title"><div className="desk-strip-heading"><div><span className="eyebrow">Desk at a glance</span><h2 id="snapshot-title">What the desk knows now.</h2></div><span className="data-note"><span className="status-dot" />Cached public data</span></div><div className="desk-snapshot-grid"><SnapshotItem label="XAUUSD status" value={signal?.signal_type || "No verified signal"} detail={signal?.symbol || "Awaiting a published market row"} /><SnapshotItem label="Signal access" value={signal ? "Published teaser" : "No active teaser"} detail={signal?.timeframe ? `${signal.timeframe} context available` : "Open the signal desk for available public context"} href="/signals" /><SnapshotItem label="Latest analysis" value={latest?.title || "Research unavailable"} detail={latest?.category_title || "Published editorial research"} href={latest ? `/blog/${latest.slug}` : "/blog"} /><SnapshotItem label="Last public update" value={formatUpdateTime(updateTime)} detail="Published public data" /></div></section>

    <section id="deliverables" className="home-section home-deliverables" aria-labelledby="deliverables-title"><header className="editorial-heading"><div><span className="eyebrow">What you get</span><h2 id="deliverables-title">A research system designed to reduce noise.</h2></div><p>Not one isolated signal card. A connected set of public, protected and evidence-led research layers.</p></header><div className="deliverable-grid">{deliverables.map(([number, title, text]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>

    <section id="capabilities" className="home-section home-tools" aria-labelledby="tools-title"><header className="editorial-heading"><div><span className="eyebrow">Research capabilities</span><h2 id="tools-title">One intelligence layer.<br /><em>Every angle considered.</em></h2></div><p>Purpose-built tools for readers who want context, defined risk and less market noise.</p></header><div className="capability-tabs" aria-label="Capability categories"><span className="active">All</span><span>Signals</span><span>Analysis</span><span>Risk</span><span>Astrology</span><span>AI</span></div><div className="research-tool-grid">{researchTools.map((tool, index) => <ResearchToolCard {...tool} index={index + 1} key={tool.title} />)}</div></section>

    <section id="audience" className="home-section audience-section" aria-labelledby="audience-title"><header className="editorial-heading"><div><span className="eyebrow">Who it is for</span><h2 id="audience-title">Built for people who want a process, not a promise.</h2></div><p>Each use case starts with the problem and ends with a clearer research output—not a guaranteed market outcome.</p></header><div className="audience-grid">{audiences.map(([title, l1, p1, l2, p2, l3, p3]) => <article key={title}><h3>{title}</h3><dl><div><dt>{l1}</dt><dd>{p1}</dd></div><div><dt>{l2}</dt><dd>{p2}</dd></div><div><dt>{l3}</dt><dd>{p3}</dd></div></dl></article>)}</div></section>

    <section id="modules" className="home-section modules-section" aria-labelledby="modules-title"><div className="module-visual"><Image src="/images/home/venusrealm-gold-desk-hero.png" alt="Gold research desk visual" fill sizes="(max-width: 760px) 100vw, 44vw" /></div><div className="module-copy"><span className="eyebrow">Core desk modules</span><h2 id="modules-title">From public context to protected member access.</h2><p>Each module has a clear role so public research, member-only signal detail and verified outcomes do not blur together.</p><div className="module-list">{modules.map(([title, text, href], index) => <Link href={href} key={title}><span>0{index + 1}</span><div><strong>{title}</strong><small>{text}</small></div><Icon name="arrow" size={18} /></Link>)}</div></div></section>

    <section className="levels-section" aria-labelledby="signals-title"><header className="levels-heading"><div><span className="eyebrow">Live research layer</span><h2 id="signals-title">Defined context.<br />Protected levels.</h2></div><div><p>The homepage shows non-actionable public teasers only. Detailed entry, stop-loss and target levels remain inside the appropriate signal access flow.</p><Link className="text-link" href="/signals">Open signal desk <Icon name="arrow" size={16} /></Link></div></header>{signals.length ? <div className="premium-signal-grid">{signals.slice(0, 3).map((item, index) => <article className="premium-signal-card" key={item.id || index}><div className="signal-card-head"><span>{item.symbol || "XAUUSD"}</span><b>{item.signal_type || "WATCH"}</b></div><dl><div><dt>Timeframe</dt><dd>{item.timeframe || "—"}</dd></div><div><dt>Status</dt><dd>Published</dd></div><div><dt>Risk levels</dt><dd>Protected</dd></div><div><dt>Access</dt><dd><Link href="/signals">Open desk</Link></dd></div></dl></article>)}</div> : <div className="levels-empty"><span className="levels-empty-mark"><Icon name="clock" size={24} /></span><div><small>Desk status</small><h3>No verified signal is currently published.</h3><p>Public context will appear only when a signal clears the publishing workflow.</p></div></div>}</section>

    <section className="home-section research-section" aria-labelledby="analysis-title"><header className="editorial-heading"><div><span className="eyebrow">From the research desk</span><h2 id="analysis-title">The next considered move starts with a better question.</h2></div><Link className="text-link" href="/blog">Browse all research <Icon name="arrow" size={16} /></Link></header><ContentGrid items={publishedBlogs} /></section>

    <section className="market-narrative" aria-labelledby="narrative-title"><div className="market-narrative-image"><Image src="/images/home/venusrealm-gold-desk-hero.png" alt="Institutional gold research desk with illuminated price structure" fill sizes="(max-width: 760px) 100vw, 54vw" /></div><div className="market-narrative-copy"><span className="eyebrow">Signal is not the story</span><h2 id="narrative-title">See the structure behind the level.</h2><p>Price is only one input. VenusRealm places market structure, timing, risk and editorial context around every public insight—so you can understand the thinking before you consider the action.</p><dl><div><dt>01</dt><dd>Context before conviction</dd></div><div><dt>02</dt><dd>Invalidation before upside</dd></div><div><dt>03</dt><dd>Evidence before assertion</dd></div></dl></div></section>

    <section className="wide-lens" aria-labelledby="astrology-title"><div className="wide-lens-copy"><span className="eyebrow">The wider lens</span><h2 id="astrology-title">Timing is context,<br /><em>never certainty.</em></h2><p>Financial astrology is explored as an educational timing framework alongside market data, structure and risk—not as a standalone trading signal.</p><Link className="button button-light" href="/astrology">Explore the methodology <Icon name="arrow" size={18} /></Link></div><aside className="wide-lens-card"><span className="lens-orbit" aria-hidden="true"><Icon name="moon" size={34} /></span><small>Planetary market timing</small><strong>{astrology.length ? `${astrology.length} published insight${astrology.length === 1 ? "" : "s"}` : "Upcoming research desk"}</strong><p>{astrology.length ? astrology[0].title : "New material appears only after editorial review."}</p></aside></section>

    <section className="discipline-section" aria-labelledby="why-title"><div className="discipline-statement"><span className="eyebrow">The VenusRealm standard</span><h2 id="why-title">Built for disciplined readers.<br /><em>Not impulsive clicks.</em></h2><p>Every section prioritizes context, explicit uncertainty and educational value.</p></div><div className="discipline-list">{["Risk-first approach", "Transparent educational analysis", "Fast configured alerts", "Multi-channel updates", "Structured editorial content", "Human approval where applicable"].map((item, index) => <div key={item}><span>0{index + 1}</span><strong>{item}</strong><Icon name="check" size={17} /></div>)}</div></section>

    <section id="proof" className="proof-section" aria-labelledby="results-title"><div className="proof-copy"><span className="eyebrow">Evidence over assertion</span><h2 id="results-title">Proof should be documented,<br />not promised.</h2><p>Only evidence-backed, redacted, compliance-approved records are eligible. Account profit, ROI and unverified percentages are never inferred.</p><Link className="text-link" href="/results">Read methodology and records <Icon name="arrow" size={16} /></Link></div><div className="proof-card"><span className="proof-seal"><Icon name="target" size={26} /></span><small>Verified public record</small>{results.length ? <><strong>{results[0].symbol} {results[0].direction}</strong><span>{results[0].result_points} {results[0].result_unit}</span><p>{results[0].public_summary}</p></> : <><strong>Awaiting verified records</strong><p>No synthetic claims or placeholder percentages are shown.</p></>}</div></section>

    <section className="membership-section" aria-labelledby="membership-title"><div><span className="eyebrow">Member access</span><h2 id="membership-title">A clear path from public research to protected detail.</h2><p>Public visitors can explore methodology and teaser context. Verified paid members can access the protected signal desk through the existing secure member flow.</p></div><div className="membership-steps"><span><b>01</b> Create account</span><span><b>02</b> Verify email</span><span><b>03</b> Submit payment reference</span><span><b>04</b> Access after verification</span></div><div className="membership-actions"><Link className="button button-dark" href="/login">Member access</Link><Link className="text-link" href="/signup">Create account <Icon name="arrow" size={15} /></Link></div></section>

    <section className="video-section editorial-video" aria-labelledby="video-title"><div><span className="eyebrow">Watch the desk</span><h2 id="video-title">See the research process.</h2><p>{links.video || links.youtube ? "Open the configured VenusRealm video channel for published market education." : "No public video channel is configured for this preview. No placeholder videos are loaded."}</p></div>{(links.video || links.youtube) && <a className="button button-dark" href={links.video || links.youtube} rel="noreferrer" target="_blank">Open YouTube <Icon name="arrow" size={18} /></a>}</section>

    <section id="faq" className="home-section faq-section" aria-labelledby="faq-title"><header className="editorial-heading faq-heading"><div><span className="eyebrow">Frequently asked</span><h2 id="faq-title">Straight answers before you enter the desk.</h2></div><p>How access works, what is public, what stays protected and where your responsibility begins.</p></header><div className="editorial-faq"><FaqItem number="01" question="Are signals financial advice?">No. Signals and analysis are educational information and do not account for your circumstances. You remain responsible for every financial decision.</FaqItem><FaqItem number="02" question="What can a public visitor see?">Public pages may show publication status, symbol, signal type, timeframe and educational context. Protected entry, stop-loss and target levels are not shown on the homepage.</FaqItem><FaqItem number="03" question="How do member signals work?">A valid member session and verified access state are required before protected signal detail is requested through the existing member flow.</FaqItem><FaqItem number="04" question="Is astrology used alone?">No. Astrology is an educational timing lens and never replaces market structure, risk management or independent judgment.</FaqItem><FaqItem number="05" question="How are results presented?">Only evidence-backed public records that pass privacy and publication controls are shown. VenusRealm does not infer ROI, account profit or win rate.</FaqItem><FaqItem number="06" question="Where are alerts delivered?">Alerts appear on the signal desk. Telegram or WhatsApp destinations are shown only when those channels are configured.</FaqItem><FaqItem number="07" question="What are the risks?">Gold and leveraged markets can move quickly. Losses may exceed expectations, past results do not predict future outcomes, and no signal guarantees a result.</FaqItem></div></section>
  </div>;
}

function formatUpdateTime(value: string | undefined) {
  if (!value) return "Not available";
  return new Intl.DateTimeFormat("en", { day: "numeric", month: "short", hour: "2-digit", minute: "2-digit" }).format(new Date(value));
}
