import Image from "next/image";
import Link from "next/link";
import { FaqItem, InsightCard, ProcessStep, ResearchToolCard, SnapshotItem } from "@/components/homepage-sections";
import { ContentGrid } from "@/components/content-grid";
import { Icon, type IconName } from "@/components/icon";
import { getContent, getResultSnapshot, getSignalSnapshot } from "@/lib/api";
import { configuredLinks } from "@/lib/site-config";

export const revalidate = 300;

const tools: { icon: IconName; title: string; text: string; href: string }[] = [
  { icon: "gold", title: "Gold signals", text: "Structured XAUUSD levels with entries, invalidation and clear risk context.", href: "/signals" },
  { icon: "chart", title: "Market analysis", text: "Technical and macro research built for considered decisions—not reaction.", href: "/category/analysis-department" },
  { icon: "moon", title: "Financial astrology", text: "An educational exploration of planetary cycles and market timing.", href: "/astrology" },
  { icon: "book", title: "Market learning", text: "Practical education grounded in process, discipline and risk control.", href: "/category/market-education" },
  { icon: "brain", title: "AI research", text: "AI-assisted synthesis with explicit risk framing and editorial review.", href: "/blog" },
];

export default async function HomePage() {
  const [content, signals, results] = await Promise.all([getContent(undefined, 12), getSignalSnapshot(), getResultSnapshot()]);
  const publishedBlogs = content.filter((item) => ["BLOG", "AI_BLOG", "ANALYSIS", "EDUCATION", "ADVISORY"].includes(item.content_type)).slice(0, 6);
  const astrology = content.filter((item) => `${item.title} ${item.excerpt || ""} ${item.category_title || ""}`.toLowerCase().includes("astrolog"));
  const latest = publishedBlogs[0];
  const signal = signals[0];
  const links = configuredLinks();
  const researchTools = links.telegram ? [...tools, { icon: "send" as IconName, title: "Telegram alerts", text: "Fast channel delivery when a verified public alert is available.", href: links.telegram }] : tools;
  const updateTime = signal?.updated_at || signal?.published_at || signal?.signal_time || latest?.published_at || latest?.created_at;

  return <div className="home-page">
    <section className="home-hero">
      <Image className="home-hero-art" src="/images/home/venusrealm-gold-desk-hero.png" alt="Gold bars and market charts inside a premium commodities research desk" fill priority sizes="(max-width: 760px) 100vw, 1240px" />
      <span className="home-hero-shade" aria-hidden="true" />
      <div className="home-hero-copy"><span className="eyebrow"><span />Independent gold intelligence</span><h1>Read gold with <em>clarity.</em><br />Act with discipline.</h1><p>VenusRealm brings XAUUSD signals, market structure, financial astrology and AI-assisted research into one calm, risk-first editorial desk.</p><div className="hero-actions"><Link className="button button-gold" href="/signals">Enter the signal desk <Icon name="arrow" size={18} /></Link><Link className="button home-button-outline" href="/blog">Read latest research</Link></div><div className="home-hero-proof" aria-label="Research principles"><span><Icon name="shield" size={15} />Risk before reward</span><span><Icon name="brain" size={15} />AI-assisted, editorially reviewed</span><span><Icon name="book" size={15} />Education, not advice</span></div></div>
      <aside className="terminal-panel" aria-label="VenusRealm research desk principles"><div className="terminal-topline"><span><i /> Research desk</span><small>Public intelligence</small></div><div className="terminal-market"><div><small>Primary market</small><strong>XAUUSD</strong></div><span className="terminal-status">Risk-first</span></div><div className="terminal-chart" aria-hidden="true"><span className="chart-line" /><span className="chart-marker marker-a" /><span className="chart-marker marker-b" /></div><div className="terminal-principles"><InsightCard index="01" label="Structure" value="Before signal" /><InsightCard index="02" label="Context" value="Before conviction" /><InsightCard index="03" label="Risk" value="Before reward" /></div><p>Every public insight moves through a controlled research and publishing workflow.</p></aside>
    </section>

    <section className="desk-strip" aria-labelledby="snapshot-title"><div className="desk-strip-heading"><div><span className="eyebrow">Desk at a glance</span><h2 id="snapshot-title">What the desk knows now.</h2></div><span className="data-note"><span className="status-dot" />Cached public data</span></div><div className="desk-snapshot-grid"><SnapshotItem label="XAUUSD status" value={signal?.signal_type || "No verified signal"} detail={signal?.symbol || "Awaiting a published market row"} /><SnapshotItem label="Signal access" value={signal ? "Published teaser" : "No active teaser"} detail={signal?.timeframe ? `${signal.timeframe} context available` : "Open the signal desk for available public context"} href="/signals" /><SnapshotItem label="Latest analysis" value={latest?.title || "Research unavailable"} detail={latest?.category_title || "Published editorial research"} href={latest ? `/blog/${latest.slug}` : "/blog"} /><SnapshotItem label="Last public update" value={formatUpdateTime(updateTime)} detail="Published public data" /></div></section>

    <section className="home-section home-tools" aria-labelledby="tools-title"><header className="editorial-heading"><div><span className="eyebrow">Research instruments</span><h2 id="tools-title">One intelligence layer.<br /><em>Every angle considered.</em></h2></div><p>Purpose-built tools for readers who want context, defined risk and less market noise.</p></header><div className="research-tool-grid">{researchTools.map((tool, index) => <ResearchToolCard {...tool} index={index + 1} key={tool.title} />)}</div></section>

    <section className="levels-section" aria-labelledby="signals-title"><header className="levels-heading"><div><span className="eyebrow">Live research layer</span><h2 id="signals-title">Defined context.<br />Protected levels.</h2></div><div><p>The homepage shows non-actionable public teasers only. Detailed entry, stop-loss and target levels remain inside the appropriate signal access flow.</p><Link className="text-link" href="/signals">Open signal desk <Icon name="arrow" size={16} /></Link></div></header>{signals.length ? <div className="premium-signal-grid">{signals.slice(0, 3).map((item, index) => <article className="premium-signal-card" key={item.id || index}><div className="signal-card-head"><span>{item.symbol || "XAUUSD"}</span><b>{item.signal_type || "WATCH"}</b></div><dl><div><dt>Timeframe</dt><dd>{item.timeframe || "—"}</dd></div><div><dt>Status</dt><dd>Published</dd></div><div><dt>Risk levels</dt><dd>Protected</dd></div><div><dt>Access</dt><dd><Link href="/signals">Open desk</Link></dd></div></dl></article>)}</div> : <div className="levels-empty"><span className="levels-empty-mark"><Icon name="clock" size={24} /></span><div><small>Desk status</small><h3>No verified signal is currently published.</h3><p>Public context will appear only when a signal clears the publishing workflow.</p></div></div>}</section>

    <section className="home-section research-section" aria-labelledby="analysis-title"><header className="editorial-heading"><div><span className="eyebrow">From the research desk</span><h2 id="analysis-title">The next considered move starts with a better question.</h2></div><Link className="text-link" href="/blog">Browse all research <Icon name="arrow" size={16} /></Link></header><ContentGrid items={publishedBlogs} /></section>

    <section className="market-narrative" aria-labelledby="narrative-title"><div className="market-narrative-image"><Image src="/images/home/venusrealm-gold-desk-hero.png" alt="Institutional gold research desk with illuminated price structure" fill sizes="(max-width: 760px) 100vw, 54vw" /></div><div className="market-narrative-copy"><span className="eyebrow">Signal is not the story</span><h2 id="narrative-title">See the structure behind the level.</h2><p>Price is only one input. VenusRealm places market structure, timing, risk and editorial context around every public insight—so you can understand the thinking before you consider the action.</p><dl><div><dt>01</dt><dd>Context before conviction</dd></div><div><dt>02</dt><dd>Invalidation before upside</dd></div><div><dt>03</dt><dd>Evidence before assertion</dd></div></dl></div></section>

    <section className="wide-lens" aria-labelledby="astrology-title"><div className="wide-lens-copy"><span className="eyebrow">The wider lens</span><h2 id="astrology-title">Timing is context,<br /><em>never certainty.</em></h2><p>Financial astrology is explored as an educational timing framework alongside market data, structure and risk—not as a standalone trading signal.</p><Link className="button button-light" href="/astrology">Explore the methodology <Icon name="arrow" size={18} /></Link></div><aside className="wide-lens-card"><span className="lens-orbit" aria-hidden="true"><Icon name="moon" size={34} /></span><small>Planetary market timing</small><strong>{astrology.length ? `${astrology.length} published insight${astrology.length === 1 ? "" : "s"}` : "Upcoming research desk"}</strong><p>{astrology.length ? astrology[0].title : "New material appears only after editorial review."}</p></aside></section>

    <section id="how-it-works" className="home-section process-section" aria-labelledby="process-title"><header className="editorial-heading centered-editorial"><div><span className="eyebrow">Research protocol</span><h2 id="process-title">From market input<br />to public insight.</h2></div><p>A deliberate workflow designed to keep fact, interpretation and risk in the right order.</p></header><ol className="editorial-process"><ProcessStep number="01" icon="globe" title="Market data" text="Published inputs and price context establish the factual base." /><ProcessStep number="02" icon="brain" title="Synthesis" text="Research tools examine structure, narrative and timing frameworks." /><ProcessStep number="03" icon="shield" title="Risk review" text="Claims, levels and language pass through a risk-first lens." /><ProcessStep number="04" icon="send" title="Publication" text="Approved public intelligence reaches the site and configured channels." /></ol></section>

    <section className="discipline-section" aria-labelledby="why-title"><div className="discipline-statement"><span className="eyebrow">The VenusRealm standard</span><h2 id="why-title">Built for disciplined readers.<br /><em>Not impulsive clicks.</em></h2><p>Every section prioritizes context, explicit uncertainty and educational value.</p></div><div className="discipline-list">{["Risk-first approach", "Transparent educational analysis", "Fast configured alerts", "Multi-channel updates", "Structured editorial content", "Human approval where applicable"].map((item, index) => <div key={item}><span>0{index + 1}</span><strong>{item}</strong><Icon name="check" size={17} /></div>)}</div></section>

    <section id="results" className="proof-section" aria-labelledby="results-title"><div className="proof-copy"><span className="eyebrow">Evidence over assertion</span><h2 id="results-title">Proof should be documented,<br />not promised.</h2><p>Only evidence-backed, redacted, compliance-approved records are eligible. Account profit, ROI and unverified percentages are never inferred.</p><Link className="text-link" href="/results">Read methodology and records <Icon name="arrow" size={16} /></Link></div><div className="proof-card"><span className="proof-seal"><Icon name="target" size={26} /></span><small>Verified public record</small>{results.length ? <><strong>{results[0].symbol} {results[0].direction}</strong><span>{results[0].result_points} {results[0].result_unit}</span><p>{results[0].public_summary}</p></> : <><strong>Awaiting verified records</strong><p>No synthetic claims or placeholder percentages are shown.</p></>}</div></section>

    <section className="video-section editorial-video" aria-labelledby="video-title"><div><span className="eyebrow">Watch the desk</span><h2 id="video-title">See the research process.</h2><p>{links.video || links.youtube ? "Open the configured VenusRealm video channel for published market education." : "No public video channel is configured for this preview. No placeholder videos are loaded."}</p></div>{(links.video || links.youtube) && <a className="button button-dark" href={links.video || links.youtube} rel="noreferrer" target="_blank">Open YouTube <Icon name="arrow" size={18} /></a>}</section>

    <section id="faq" className="home-section faq-section" aria-labelledby="faq-title"><header className="editorial-heading faq-heading"><div><span className="eyebrow">Before you begin</span><h2 id="faq-title">Clear answers.<br />No fine-print thinking.</h2></div><p>How the research works, what it can do, and where your responsibility begins.</p></header><div className="editorial-faq"><FaqItem number="01" question="Are signals financial advice?">No. Signals and analysis are educational information and do not account for your circumstances. You remain responsible for every financial decision.</FaqItem><FaqItem number="02" question="How are signals created?">Public signals may combine market data, structured analysis and automated research, followed by the approval controls applicable to the publishing workflow.</FaqItem><FaqItem number="03" question="Is astrology used alone?">No. Astrology is an educational timing lens and never replaces market structure, risk management or independent judgment.</FaqItem><FaqItem number="04" question="Where are alerts delivered?">Alerts appear on the public signal desk. Telegram or WhatsApp links are shown only when those public channels are configured.</FaqItem><FaqItem number="05" question="What are the risks?">Gold and leveraged markets can move quickly. Losses may exceed expectations, past results do not predict future outcomes, and no signal guarantees a result.</FaqItem></div></section>

    <section className="home-final-cta"><span className="cta-orbit" aria-hidden="true" /><div><span className="eyebrow">Read the market differently</span><h2>Clarity for gold.<br /><em>Discipline for every decision.</em></h2></div><div className="cta-actions"><Link className="button button-gold" href="/signals">View signals <Icon name="arrow" size={18} /></Link>{links.telegram && <a className="button button-light" href={links.telegram} rel="noreferrer" target="_blank">Join Telegram</a>}<Link className="button home-button-outline" href="/blog">Latest analysis</Link></div></section>
  </div>;
}

function formatUpdateTime(value: string | undefined) {
  if (!value) return "Not available";
  return new Intl.DateTimeFormat("en", { day: "numeric", month: "short", hour: "2-digit", minute: "2-digit" }).format(new Date(value));
}
