-- Market signal storage and durable Telegram delivery tracking.

BEGIN;

CREATE TABLE IF NOT EXISTS public.market_signals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL DEFAULT 'XAUUSD',
    price NUMERIC(18, 6) NOT NULL,
    signal_type TEXT NOT NULL,
    target_price NUMERIC(18, 6),
    stop_loss NUMERIC(18, 6),
    source TEXT NOT NULL,
    sheet_label TEXT,
    external_key TEXT,
    signal_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    telegram_sent_at TIMESTAMPTZ,
    telegram_message_id TEXT,
    delivery_error TEXT
);

ALTER TABLE public.market_signals
    ADD COLUMN IF NOT EXISTS symbol TEXT NOT NULL DEFAULT 'XAUUSD',
    ADD COLUMN IF NOT EXISTS price NUMERIC(18, 6),
    ADD COLUMN IF NOT EXISTS signal_type TEXT,
    ADD COLUMN IF NOT EXISTS target_price NUMERIC(18, 6),
    ADD COLUMN IF NOT EXISTS stop_loss NUMERIC(18, 6),
    ADD COLUMN IF NOT EXISTS source TEXT NOT NULL DEFAULT 'UNKNOWN',
    ADD COLUMN IF NOT EXISTS sheet_label TEXT,
    ADD COLUMN IF NOT EXISTS external_key TEXT,
    ADD COLUMN IF NOT EXISTS signal_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS telegram_sent_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS telegram_message_id TEXT,
    ADD COLUMN IF NOT EXISTS delivery_error TEXT;

ALTER TABLE public.market_signals
    DROP CONSTRAINT IF EXISTS market_signals_signal_type_check;

ALTER TABLE public.market_signals
    ADD CONSTRAINT market_signals_signal_type_check
        CHECK (signal_type IN ('BUY', 'SELL', 'HOLD'));

CREATE UNIQUE INDEX IF NOT EXISTS market_signals_external_key_unique
    ON public.market_signals (external_key)
    WHERE external_key IS NOT NULL;

CREATE INDEX IF NOT EXISTS market_signals_pending_telegram_idx
    ON public.market_signals (signal_time)
    WHERE signal_type IN ('BUY', 'SELL')
      AND telegram_sent_at IS NULL;

CREATE OR REPLACE FUNCTION public.reset_market_signal_delivery()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    IF ROW(
        NEW.price,
        NEW.signal_type,
        NEW.target_price,
        NEW.stop_loss,
        NEW.sheet_label
    ) IS DISTINCT FROM ROW(
        OLD.price,
        OLD.signal_type,
        OLD.target_price,
        OLD.stop_loss,
        OLD.sheet_label
    ) THEN
        NEW.telegram_sent_at = NULL;
        NEW.telegram_message_id = NULL;
        NEW.delivery_error = NULL;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS market_signals_reset_delivery
    ON public.market_signals;
CREATE TRIGGER market_signals_reset_delivery
BEFORE UPDATE ON public.market_signals
FOR EACH ROW
EXECUTE FUNCTION public.reset_market_signal_delivery();

ALTER TABLE public.market_signals ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.market_signals FROM anon, authenticated;

COMMIT;
