-- Public website content, subscriptions, payment review, and secure settings.

BEGIN;

ALTER TABLE public.users
    ADD COLUMN IF NOT EXISTS payment_status TEXT NOT NULL DEFAULT 'NOT_STARTED';

UPDATE public.users
SET payment_status = CASE
    WHEN approval_status = 'APPROVED' THEN 'VERIFIED'
    WHEN approval_status = 'BLOCKED' THEN 'REJECTED'
    ELSE 'NOT_STARTED'
END
WHERE payment_status = 'NOT_STARTED';

ALTER TABLE public.users
    DROP CONSTRAINT IF EXISTS users_payment_status_check;

ALTER TABLE public.users
    ADD CONSTRAINT users_payment_status_check
    CHECK (
        payment_status IN (
            'NOT_STARTED',
            'PENDING',
            'UNDER_REVIEW',
            'VERIFIED',
            'REJECTED'
        )
    );

CREATE TABLE IF NOT EXISTS public.subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    plan_name TEXT NOT NULL DEFAULT 'VIP',
    amount_usdt NUMERIC(18, 6),
    network TEXT,
    transaction_id TEXT,
    payment_status TEXT NOT NULL DEFAULT 'PENDING',
    submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    reviewed_at TIMESTAMPTZ,
    reviewed_by BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    review_note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT subscriptions_payment_status_check CHECK (
        payment_status IN (
            'NOT_STARTED',
            'PENDING',
            'UNDER_REVIEW',
            'VERIFIED',
            'REJECTED'
        )
    )
);

CREATE INDEX IF NOT EXISTS subscriptions_user_status_idx
    ON public.subscriptions (user_id, payment_status);

CREATE UNIQUE INDEX IF NOT EXISTS subscriptions_active_txid_unique
    ON public.subscriptions (transaction_id)
    WHERE transaction_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.content_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    description TEXT,
    icon TEXT,
    display_order INTEGER NOT NULL DEFAULT 0,
    is_public BOOLEAN NOT NULL DEFAULT TRUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.content_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT REFERENCES public.content_categories(id)
        ON DELETE SET NULL,
    content_type TEXT NOT NULL,
    title TEXT NOT NULL,
    excerpt TEXT,
    body TEXT,
    image_url TEXT,
    external_url TEXT,
    is_public BOOLEAN NOT NULL DEFAULT TRUE,
    is_published BOOLEAN NOT NULL DEFAULT FALSE,
    published_at TIMESTAMPTZ,
    created_by BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT content_items_type_check CHECK (
        content_type IN (
            'SPECIAL_ZONE',
            'ADVISORY',
            'ANALYSIS',
            'EDUCATION',
            'AI_BLOG',
            'ANNOUNCEMENT',
            'PROFIT_SCREENSHOT'
        )
    )
);

CREATE INDEX IF NOT EXISTS content_items_public_idx
    ON public.content_items (content_type, published_at DESC)
    WHERE is_public = TRUE AND is_published = TRUE;

CREATE TABLE IF NOT EXISTS public.site_settings (
    setting_key TEXT PRIMARY KEY,
    setting_value TEXT,
    is_sensitive BOOLEAN NOT NULL DEFAULT TRUE,
    updated_by BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO public.content_categories
    (slug, title, description, icon, display_order)
VALUES
    ('xauusd-signals', 'XAUUSD Signals',
     'Structured gold market signals and execution levels.', '🥇', 10),
    ('crypto-signals', 'Crypto Signals',
     'Curated digital-asset opportunities and market alerts.', '₿', 20),
    ('special-zone', 'Special Zone',
     'Member-focused opportunities and high-priority updates.', '⚡', 30),
    ('advisory', 'Advisory',
     'Risk-aware market guidance and trading discipline.', '🛡️', 40),
    ('analysis-department', 'Analysis Department',
     'Technical and macro market research.', '📊', 50),
    ('market-education', 'Market Education',
     'Trading concepts, risk controls, and learning resources.', '🎓', 60),
    ('ai-blog', 'AI Blog',
     'Published market content prepared by the research workflow.', '✦', 70),
    ('announcements', 'Announcements',
     'Service, festival, and market announcements.', '📣', 80),
    ('profit-screenshots', 'Profit Screenshots',
     'Published community trading-result snapshots.', '🏆', 90),
    ('payment-subscription', 'Payment / Subscription',
     'Secure subscription verification and access information.', '💳', 100),
    ('contact-support', 'Contact / Support',
     'Verified-member support and assistance.', '💬', 110)
ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    icon = EXCLUDED.icon,
    display_order = EXCLUDED.display_order;

DROP TRIGGER IF EXISTS subscriptions_set_updated_at
    ON public.subscriptions;
CREATE TRIGGER subscriptions_set_updated_at
BEFORE UPDATE ON public.subscriptions
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS content_categories_set_updated_at
    ON public.content_categories;
CREATE TRIGGER content_categories_set_updated_at
BEFORE UPDATE ON public.content_categories
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS content_items_set_updated_at
    ON public.content_items;
CREATE TRIGGER content_items_set_updated_at
BEFORE UPDATE ON public.content_items
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.content_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.content_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.subscriptions FROM anon, authenticated;
REVOKE ALL ON TABLE public.content_categories FROM anon, authenticated;
REVOKE ALL ON TABLE public.content_items FROM anon, authenticated;
REVOKE ALL ON TABLE public.site_settings FROM anon, authenticated;

INSERT INTO storage.buckets (id, name, public)
VALUES ('profit-screenshots', 'profit-screenshots', TRUE)
ON CONFLICT (id) DO UPDATE SET public = TRUE;

COMMIT;
