-- Tables required by the Admin Overview aggregate metrics.
-- This migration is idempotent and preserves all existing data.

BEGIN;

CREATE TABLE IF NOT EXISTS public.subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    plan_name TEXT NOT NULL DEFAULT 'VIP',
    amount_usdt NUMERIC(18, 6),
    network TEXT,
    transaction_id TEXT,
    payment_status TEXT NOT NULL DEFAULT 'PENDING',
    submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    reviewed_at TIMESTAMPTZ,
    reviewed_by BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    review_note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT subscriptions_payment_status_check CHECK (
        payment_status IN (
            'NOT_STARTED',
            'PENDING',
            'UNDER_REVIEW',
            'VERIFIED',
            'REJECTED'
        )
    )
);

CREATE TABLE IF NOT EXISTS public.content_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    description TEXT,
    icon TEXT,
    display_order INTEGER NOT NULL DEFAULT 0,
    is_public BOOLEAN NOT NULL DEFAULT TRUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.content_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT REFERENCES public.content_categories(id)
        ON DELETE SET NULL,
    content_type TEXT NOT NULL,
    title TEXT NOT NULL,
    excerpt TEXT,
    body TEXT,
    image_url TEXT,
    external_url TEXT,
    is_public BOOLEAN NOT NULL DEFAULT TRUE,
    is_published BOOLEAN NOT NULL DEFAULT FALSE,
    published_at TIMESTAMPTZ,
    created_by BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT content_items_type_check CHECK (
        content_type IN (
            'SPECIAL_ZONE',
            'ADVISORY',
            'ANALYSIS',
            'EDUCATION',
            'AI_BLOG',
            'ANNOUNCEMENT',
            'PROFIT_SCREENSHOT'
        )
    )
);

CREATE INDEX IF NOT EXISTS subscriptions_user_status_idx
    ON public.subscriptions (user_id, payment_status);

CREATE UNIQUE INDEX IF NOT EXISTS subscriptions_active_txid_unique
    ON public.subscriptions (transaction_id)
    WHERE transaction_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS content_items_public_idx
    ON public.content_items (content_type, published_at DESC)
    WHERE is_public = TRUE AND is_published = TRUE;

ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.content_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.content_items ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.subscriptions FROM anon, authenticated;
REVOKE ALL ON TABLE public.content_categories FROM anon, authenticated;
REVOKE ALL ON TABLE public.content_items FROM anon, authenticated;

COMMIT;
