-- Admin-only AI-agent configuration and execution audit history.

BEGIN;

CREATE TABLE IF NOT EXISTS public.ai_agents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_key TEXT NOT NULL UNIQUE,
    display_name TEXT NOT NULL,
    display_order INTEGER NOT NULL DEFAULT 0,
    is_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    status TEXT NOT NULL DEFAULT 'IDLE',
    last_run_at TIMESTAMPTZ,
    last_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ai_agents_status_check
        CHECK (status IN ('IDLE', 'RUNNING', 'ERROR'))
);

CREATE TABLE IF NOT EXISTS public.ai_agent_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id BIGINT NOT NULL
        REFERENCES public.ai_agents(id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'RUNNING',
    triggered_by BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    finished_at TIMESTAMPTZ,
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ai_agent_runs_status_check
        CHECK (status IN ('RUNNING', 'SUCCESS', 'ERROR'))
);

CREATE INDEX IF NOT EXISTS ai_agents_status_idx
    ON public.ai_agents (is_enabled, status);

CREATE INDEX IF NOT EXISTS ai_agent_runs_agent_started_idx
    ON public.ai_agent_runs (agent_id, started_at DESC);

INSERT INTO public.ai_agents (
    agent_key, display_name, display_order
)
VALUES
    ('ai_blog_agent', 'AI Blog Agent', 10),
    ('telegram_reply_agent', 'Telegram Reply Agent', 20),
    ('whatsapp_reply_agent', 'WhatsApp Reply Agent', 30),
    ('signal_agent', 'Signal Agent', 40),
    ('announcement_agent', 'Announcement Agent', 50),
    ('seo_agent', 'SEO Agent', 60),
    ('image_agent', 'Image Agent', 70)
ON CONFLICT (agent_key) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    display_order = EXCLUDED.display_order,
    updated_at = NOW();

ALTER TABLE public.ai_agents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_agent_runs ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.ai_agents FROM anon, authenticated;
REVOKE ALL ON TABLE public.ai_agent_runs FROM anon, authenticated;

COMMIT;
