-- Production agent queue, scheduling, conversations, content SEO and delivery.

ALTER TABLE public.ai_agents
    ADD COLUMN IF NOT EXISTS schedule_minutes INTEGER,
    ADD COLUMN IF NOT EXISTS next_scheduled_run_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS success_count BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS failure_count BIGINT NOT NULL DEFAULT 0;

ALTER TABLE public.ai_agent_runs
    ADD COLUMN IF NOT EXISTS trigger_type TEXT NOT NULL DEFAULT 'MANUAL',
    ADD COLUMN IF NOT EXISTS duration_ms BIGINT,
    ADD COLUMN IF NOT EXISTS result_summary TEXT;

CREATE TABLE IF NOT EXISTS public.ai_agent_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id BIGINT NOT NULL REFERENCES public.ai_agents(id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'QUEUED'
        CHECK (status IN ('QUEUED', 'RUNNING', 'SUCCESS', 'ERROR')),
    priority INTEGER NOT NULL DEFAULT 0,
    payload JSONB NOT NULL DEFAULT '{}'::JSONB,
    triggered_by BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    worker_id TEXT,
    attempts INTEGER NOT NULL DEFAULT 0,
    available_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    last_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ai_agent_jobs_claim_idx
    ON public.ai_agent_jobs (status, priority DESC, available_at, created_at);

CREATE TABLE IF NOT EXISTS public.ai_agent_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id BIGINT NOT NULL UNIQUE
        REFERENCES public.ai_agents(id) ON DELETE CASCADE,
    interval_minutes INTEGER NOT NULL CHECK (interval_minutes >= 1),
    payload JSONB NOT NULL DEFAULT '{}'::JSONB,
    is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    next_run_at TIMESTAMPTZ NOT NULL,
    last_enqueued_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.worker_heartbeats (
    worker_id TEXT PRIMARY KEY,
    heartbeat_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS public.ai_conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel TEXT NOT NULL CHECK (channel IN ('TELEGRAM', 'WHATSAPP')),
    external_user_id TEXT NOT NULL,
    human_takeover_until TIMESTAMPTZ,
    last_message_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (channel, external_user_id)
);

CREATE TABLE IF NOT EXISTS public.ai_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL
        REFERENCES public.ai_conversations(id) ON DELETE CASCADE,
    sender_type TEXT NOT NULL
        CHECK (sender_type IN ('USER', 'AI', 'ADMIN')),
    body TEXT NOT NULL,
    media JSONB NOT NULL DEFAULT '{}'::JSONB,
    external_message_id TEXT,
    admin_user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (conversation_id, external_message_id)
);

CREATE INDEX IF NOT EXISTS ai_messages_conversation_idx
    ON public.ai_messages (conversation_id, created_at DESC);

CREATE TABLE IF NOT EXISTS public.content_seo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id BIGINT NOT NULL UNIQUE
        REFERENCES public.content_items(id) ON DELETE CASCADE,
    slug TEXT NOT NULL UNIQUE,
    meta_title TEXT,
    meta_description TEXT,
    focus_keyword TEXT,
    internal_links JSONB NOT NULL DEFAULT '[]'::JSONB,
    faq JSONB NOT NULL DEFAULT '[]'::JSONB,
    schema_jsonld JSONB NOT NULL DEFAULT '{}'::JSONB,
    open_graph JSONB NOT NULL DEFAULT '{}'::JSONB,
    twitter_card JSONB NOT NULL DEFAULT '{}'::JSONB,
    image_prompt TEXT,
    audit_issues JSONB NOT NULL DEFAULT '[]'::JSONB,
    last_audited_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'SCHEDULED'
        CHECK (status IN ('SCHEDULED', 'QUEUED', 'SENT', 'PARTIAL', 'ERROR')),
    send_telegram BOOLEAN NOT NULL DEFAULT TRUE,
    send_whatsapp BOOLEAN NOT NULL DEFAULT TRUE,
    scheduled_at TIMESTAMPTZ,
    sent_at TIMESTAMPTZ,
    created_by BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.announcement_deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    announcement_id BIGINT NOT NULL
        REFERENCES public.announcements(id) ON DELETE CASCADE,
    channel TEXT NOT NULL CHECK (channel IN ('TELEGRAM', 'WHATSAPP')),
    recipient TEXT,
    status TEXT NOT NULL CHECK (status IN ('DELIVERED', 'ERROR')),
    external_message_id TEXT,
    error_message TEXT,
    delivered_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.market_signals
    ADD COLUMN IF NOT EXISTS tp2 NUMERIC(18, 6),
    ADD COLUMN IF NOT EXISTS confidence NUMERIC(5, 2),
    ADD COLUMN IF NOT EXISTS risk_notes TEXT,
    ADD COLUMN IF NOT EXISTS website_published_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS whatsapp_sent_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS whatsapp_delivery_error TEXT;

CREATE OR REPLACE FUNCTION public.enqueue_due_ai_agent_schedules()
RETURNS TABLE(job_id BIGINT)
LANGUAGE plpgsql
SECURITY INVOKER
AS $$
BEGIN
    RETURN QUERY
    WITH due AS (
        SELECT s.id, s.agent_id, s.payload, s.interval_minutes
        FROM public.ai_agent_schedules s
        JOIN public.ai_agents a ON a.id = s.agent_id
        WHERE s.is_enabled = TRUE
          AND a.is_enabled = TRUE
          AND s.next_run_at <= NOW()
        FOR UPDATE OF s SKIP LOCKED
    ), queued AS (
        INSERT INTO public.ai_agent_jobs (agent_id, payload)
        SELECT agent_id, payload FROM due
        RETURNING id, agent_id
    ), advanced AS (
        UPDATE public.ai_agent_schedules s
        SET last_enqueued_at = NOW(),
            next_run_at = NOW() + make_interval(
                mins => (SELECT d.interval_minutes FROM due d
                         WHERE d.id = s.id)
            ),
            updated_at = NOW()
        WHERE s.id IN (SELECT id FROM due)
        RETURNING s.agent_id
    )
    SELECT q.id FROM queued q;
END;
$$;

INSERT INTO public.ai_agent_schedules (
    agent_id, interval_minutes, next_run_at
)
SELECT id,
       CASE agent_key
           WHEN 'signal_agent' THEN 5
           WHEN 'announcement_agent' THEN 1
           WHEN 'seo_agent' THEN 1440
           ELSE 60
       END,
       NOW() + INTERVAL '5 minutes'
FROM public.ai_agents
WHERE agent_key IN ('signal_agent', 'announcement_agent', 'seo_agent')
ON CONFLICT (agent_id) DO NOTHING;

UPDATE public.ai_agents a
SET schedule_minutes = s.interval_minutes,
    next_scheduled_run_at = s.next_run_at
FROM public.ai_agent_schedules s
WHERE s.agent_id = a.id;

ALTER TABLE public.ai_agent_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_agent_schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.worker_heartbeats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.content_seo ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.announcement_deliveries ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.ai_agent_jobs FROM anon, authenticated;
REVOKE ALL ON TABLE public.ai_agent_schedules FROM anon, authenticated;
REVOKE ALL ON TABLE public.worker_heartbeats FROM anon, authenticated;
REVOKE ALL ON TABLE public.ai_conversations FROM anon, authenticated;
REVOKE ALL ON TABLE public.ai_messages FROM anon, authenticated;
REVOKE ALL ON TABLE public.content_seo FROM anon, authenticated;
REVOKE ALL ON TABLE public.announcements FROM anon, authenticated;
REVOKE ALL ON TABLE public.announcement_deliveries FROM anon, authenticated;
