-- Phase 1: isolated Next.js admin authentication foundation.
-- Additive only. Existing Streamlit authentication tables and columns remain unchanged.

BEGIN;

CREATE TABLE IF NOT EXISTS public.admin_sessions (
    token_id_hash TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ip_hash TEXT,
    user_agent_hash TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS admin_sessions_user_active_idx
    ON public.admin_sessions (user_id, expires_at DESC)
    WHERE revoked_at IS NULL;

CREATE INDEX IF NOT EXISTS admin_sessions_expiry_idx
    ON public.admin_sessions (expires_at)
    WHERE revoked_at IS NULL;

CREATE TABLE IF NOT EXISTS public.admin_login_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email_hash TEXT NOT NULL,
    ip_hash TEXT NOT NULL,
    succeeded BOOLEAN NOT NULL DEFAULT FALSE,
    attempted_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS admin_login_attempts_email_window_idx
    ON public.admin_login_attempts (email_hash, attempted_at DESC);

CREATE INDEX IF NOT EXISTS admin_login_attempts_ip_window_idx
    ON public.admin_login_attempts (ip_hash, attempted_at DESC);

CREATE TABLE IF NOT EXISTS public.admin_auth_audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    event_type TEXT NOT NULL,
    outcome TEXT NOT NULL,
    request_id TEXT NOT NULL,
    ip_hash TEXT,
    user_agent_hash TEXT,
    details JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT admin_auth_audit_outcome_check
        CHECK (outcome IN ('SUCCESS', 'DENIED', 'ERROR'))
);

CREATE INDEX IF NOT EXISTS admin_auth_audit_user_created_idx
    ON public.admin_auth_audit_events (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS admin_auth_audit_event_created_idx
    ON public.admin_auth_audit_events (event_type, created_at DESC);

ALTER TABLE public.admin_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_login_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_auth_audit_events ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.admin_sessions FROM anon, authenticated;
REVOKE ALL ON TABLE public.admin_login_attempts FROM anon, authenticated;
REVOKE ALL ON TABLE public.admin_auth_audit_events FROM anon, authenticated;

COMMIT;
