-- Phase 3A: additive media catalog and backward-compatible content linkage.

BEGIN;

CREATE TABLE IF NOT EXISTS public.media_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    storage_provider TEXT NOT NULL CHECK (storage_provider IN ('LOCAL', 'SUPABASE')),
    bucket TEXT NOT NULL,
    storage_path TEXT NOT NULL UNIQUE,
    thumbnail_path TEXT,
    public_url TEXT NOT NULL,
    thumbnail_url TEXT,
    original_filename TEXT NOT NULL,
    stored_filename TEXT NOT NULL,
    mime_type TEXT NOT NULL CHECK (mime_type IN ('image/jpeg', 'image/png', 'image/webp', 'image/gif')),
    size_bytes BIGINT NOT NULL CHECK (size_bytes > 0),
    width INTEGER NOT NULL CHECK (width > 0),
    height INTEGER NOT NULL CHECK (height > 0),
    alt_text TEXT NOT NULL DEFAULT '',
    caption TEXT NOT NULL DEFAULT '',
    source_type TEXT NOT NULL DEFAULT 'MANUAL_UPLOAD'
        CHECK (source_type IN ('MANUAL_UPLOAD', 'LOCAL_IMPORT', 'AI_GENERATED')),
    uploaded_by BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS media_assets_listing_idx
    ON public.media_assets (deleted_at, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS media_assets_source_idx
    ON public.media_assets (source_type, created_at DESC);
CREATE INDEX IF NOT EXISTS media_assets_search_idx
    ON public.media_assets (LOWER(original_filename));

ALTER TABLE public.content_items
    ADD COLUMN IF NOT EXISTS media_id BIGINT
        REFERENCES public.media_assets(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS content_items_media_id_idx
    ON public.content_items (media_id)
    WHERE media_id IS NOT NULL;

ALTER TABLE public.media_assets ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.media_assets FROM anon, authenticated;

COMMIT;
