-- Phase 5A: privacy-conscious automation service enquiries.
-- Apply only to an isolated database until production approval is given.
BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.automation_service_leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_reference UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    name TEXT NOT NULL CHECK (char_length(name) BETWEEN 2 AND 120),
    business_email TEXT NOT NULL CHECK (char_length(business_email) <= 254),
    company TEXT CHECK (company IS NULL OR char_length(company) <= 160),
    country TEXT NOT NULL CHECK (char_length(country) BETWEEN 2 AND 100),
    website_url TEXT CHECK (website_url IS NULL OR char_length(website_url) <= 2048),
    phone TEXT CHECK (phone IS NULL OR char_length(phone) <= 40),
    business_type TEXT NOT NULL CHECK (char_length(business_type) BETWEEN 2 AND 100),
    requested_services JSONB NOT NULL DEFAULT '[]'::JSONB,
    current_tools TEXT CHECK (current_tools IS NULL OR char_length(current_tools) <= 1000),
    project_description TEXT NOT NULL CHECK (char_length(project_description) BETWEEN 20 AND 5000),
    primary_problem TEXT NOT NULL CHECK (char_length(primary_problem) BETWEEN 10 AND 2000),
    expected_outcome TEXT NOT NULL CHECK (char_length(expected_outcome) BETWEEN 10 AND 2000),
    budget_range TEXT NOT NULL CHECK (char_length(budget_range) <= 80),
    preferred_timeline TEXT NOT NULL CHECK (char_length(preferred_timeline) <= 80),
    preferred_contact_method TEXT NOT NULL CHECK (preferred_contact_method IN ('EMAIL','PHONE','WHATSAPP')),
    source TEXT NOT NULL DEFAULT 'AUTOMATION_SERVICES_PAGE',
    status TEXT NOT NULL DEFAULT 'NEW' CHECK (status IN ('NEW','REVIEWING','QUALIFIED','CONTACTED','PROPOSAL','WON','LOST','SPAM','ARCHIVED','TRASHED')),
    assigned_to BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    internal_notes TEXT CHECK (internal_notes IS NULL OR char_length(internal_notes) <= 10000),
    consent_recorded_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS automation_service_leads_admin_idx
    ON public.automation_service_leads (status, updated_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS automation_service_leads_email_idx
    ON public.automation_service_leads (lower(business_email), created_at DESC);

ALTER TABLE public.automation_service_leads ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.automation_service_leads FROM anon, authenticated;

COMMIT;
