-- Durable, idempotent delivery state for sequential signal target milestones.
-- Apply only after backup/staging rehearsal and before deploying code that uses it.

BEGIN;

CREATE TABLE IF NOT EXISTS public.signal_target_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    signal_id BIGINT NOT NULL
        REFERENCES public.market_signals(id) ON DELETE CASCADE,
    target_number SMALLINT NOT NULL CHECK (target_number BETWEEN 1 AND 6),
    source_slot SMALLINT NOT NULL CHECK (source_slot BETWEEN 0 AND 6),
    target_price NUMERIC(18, 6) NOT NULL,
    achieved_price NUMERIC(18, 6) NOT NULL,
    achieved_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT signal_target_progress_signal_target_unique
        UNIQUE (signal_id, target_number)
);

CREATE TABLE IF NOT EXISTS public.signal_target_progress_deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    progress_id BIGINT NOT NULL
        REFERENCES public.signal_target_progress(id) ON DELETE CASCADE,
    channel TEXT NOT NULL CHECK (channel IN ('telegram', 'whatsapp')),
    recipient_hash CHAR(64) NOT NULL,
    claimed_at TIMESTAMPTZ,
    attempts SMALLINT NOT NULL DEFAULT 0 CHECK (attempts BETWEEN 0 AND 3),
    sent_at TIMESTAMPTZ,
    error_category TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT signal_target_progress_delivery_unique
        UNIQUE (progress_id, channel, recipient_hash)
);

CREATE INDEX IF NOT EXISTS signal_target_progress_delivery_pending_idx
    ON public.signal_target_progress_deliveries (channel, created_at)
    WHERE sent_at IS NULL AND attempts < 3;

ALTER TABLE public.signal_target_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.signal_target_progress_deliveries ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.signal_target_progress FROM anon, authenticated;
REVOKE ALL ON TABLE public.signal_target_progress_deliveries
    FROM anon, authenticated;

COMMIT;
