"""Phase 3A media validation against isolated real PostgreSQL and local files."""

from __future__ import annotations

from contextlib import contextmanager
from io import BytesIO
import os
from pathlib import Path
from types import SimpleNamespace
from typing import Iterator

import bcrypt
from fastapi import FastAPI
from fastapi.testclient import TestClient
from PIL import Image
import pytest
from sqlalchemy import create_engine, text
from sqlalchemy.orm import Session, sessionmaker

from services import admin_auth_service, admin_media_api, admin_media_service
from services.admin_media_api import router as media_router


ROOT = Path(__file__).resolve().parents[2]
DATABASE_URL = os.getenv("TEST_ADMIN_DATABASE_URL", "").strip()
pytestmark = pytest.mark.skipif(not DATABASE_URL, reason="isolated PostgreSQL is required")
PASSWORD = "Phase-3A-local-only-password!"
SETTINGS = SimpleNamespace(
    jwt_secret="phase-3a-isolated-jwt-secret-value-000000000000",
    jwt_issuer="phase-3a-local", admin_bff_shared_secret="phase-3a-bff-secret-value-000000000000",
    admin_session_ttl_minutes=15, admin_login_window_seconds=900, admin_login_max_attempts=5,
)


def png_bytes() -> bytes:
    output = BytesIO(); Image.new("RGB", (64, 40), (24, 90, 170)).save(output, "PNG"); return output.getvalue()


@pytest.fixture(scope="module")
def engine():
    db = create_engine(DATABASE_URL, pool_pre_ping=True)
    auth_sql = (ROOT / "migrations/014_admin_auth_foundation.sql").read_text()
    auth_rollback = (ROOT / "migrations/014_admin_auth_foundation.rollback.sql").read_text()
    media_sql = (ROOT / "migrations/016_admin_media_library.sql").read_text()
    media_rollback = (ROOT / "migrations/016_admin_media_library.rollback.sql").read_text()
    with db.begin() as connection:
        connection.exec_driver_sql("""
            DO $$ BEGIN CREATE ROLE anon; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
            DO $$ BEGIN CREATE ROLE authenticated; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
            CREATE TABLE public.users (
                id BIGINT PRIMARY KEY, email TEXT NOT NULL UNIQUE, password_hash TEXT,
                role TEXT NOT NULL, email_verified BOOLEAN NOT NULL,
                approval_status TEXT NOT NULL, last_login_at TIMESTAMPTZ
            );
            CREATE TABLE public.content_items (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                title TEXT NOT NULL, image_url TEXT, is_published BOOLEAN NOT NULL DEFAULT FALSE,
                deleted_at TIMESTAMPTZ, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
        """)
        connection.exec_driver_sql(auth_sql)
        connection.exec_driver_sql(media_sql)
        connection.exec_driver_sql(media_rollback)
        assert connection.execute(text("SELECT to_regclass('public.media_assets')")).scalar_one() is None
        assert connection.execute(text("SELECT COUNT(*) FROM information_schema.columns WHERE table_name='content_items' AND column_name='media_id'")).scalar_one() == 0
        connection.exec_driver_sql(media_sql)
    yield db
    with db.begin() as connection:
        connection.exec_driver_sql(media_rollback)
        connection.exec_driver_sql(auth_rollback)
        connection.exec_driver_sql("DROP TABLE public.content_items, public.users")
    db.dispose()


@pytest.fixture(autouse=True)
def isolated(engine, monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> Iterator[None]:
    factory = sessionmaker(bind=engine, expire_on_commit=False)
    with engine.begin() as connection:
        connection.execute(text("TRUNCATE admin_auth_audit_events, admin_login_attempts, admin_sessions, media_assets, content_items, users RESTART IDENTITY CASCADE"))
        password_hash = bcrypt.hashpw(PASSWORD.encode(), bcrypt.gensalt(rounds=4)).decode()
        connection.execute(text("""INSERT INTO users (id,email,password_hash,role,email_verified,approval_status) VALUES
            (1,'admin@phase3a.invalid',:hash,'ADMIN',TRUE,'APPROVED'),
            (2,'user@phase3a.invalid',:hash,'USER',TRUE,'APPROVED')"""), {"hash": password_hash})

    @contextmanager
    def scope() -> Iterator[Session]:
        session = factory()
        try: yield session; session.commit()
        except Exception: session.rollback(); raise
        finally: session.close()

    monkeypatch.setattr(admin_media_service, "session_scope", scope)
    monkeypatch.setattr(admin_auth_service, "session_scope", scope)
    monkeypatch.setattr(admin_auth_service, "get_settings", lambda: SETTINGS)
    monkeypatch.setenv("ADMIN_MEDIA_LOCAL_ROOT", str(tmp_path))
    monkeypatch.setenv("ADMIN_MEDIA_PUBLIC_BASE_URL", "http://local.invalid/media-local")
    yield


@pytest.fixture
def client() -> TestClient:
    app = FastAPI(); app.include_router(media_router); return TestClient(app)


def headers() -> dict[str, str]:
    login = admin_auth_service.login_admin(email="admin@phase3a.invalid", password=PASSWORD, ip_address="192.0.2.10", user_agent="integration", request_id="login")
    return {"Authorization": f"Bearer {login.token}", "X-Admin-BFF-Key": SETTINGS.admin_bff_shared_secret}


def upload(client: TestClient, filename: str = "chart.png"):
    return client.post("/admin/media/upload", headers=headers(), files={"file": (filename, png_bytes(), "image/png")}, data={"alt_text": "Gold market chart", "caption": "Synthetic local fixture"})


def test_migration_apply_rollback_reapply_and_upload_metadata(client: TestClient, engine) -> None:
    first = upload(client); second = upload(client)
    assert first.status_code == second.status_code == 201
    assert first.json()["stored_filename"] != second.json()["stored_filename"]
    media_id = first.json()["id"]
    updated = client.patch(f"/admin/media/{media_id}", headers=headers(), json={"alt_text": "Updated accessible chart", "caption": "Updated caption"})
    assert updated.status_code == 200 and updated.json()["alt_text"] == "Updated accessible chart"
    listing = client.get("/admin/media?search=accessible", headers=headers()).json()
    assert listing["total"] == 1 and listing["items"][0]["thumbnail_url"].endswith(".webp")
    with engine.connect() as connection:
        events = set(connection.execute(text("SELECT event_type FROM admin_auth_audit_events")).scalars())
    assert {"MEDIA_UPLOADED", "MEDIA_METADATA_UPDATED"}.issubset(events)


@pytest.mark.parametrize(("filename", "mime", "data", "expected"), [
    ("fake.jpg", "image/jpeg", png_bytes(), 400),
    ("unsafe.png", "application/x-php", png_bytes(), 400),
    ("../escape.png", "image/png", png_bytes(), 400),
    ("large.png", "image/png", b"0" * (8 * 1024 * 1024 + 1), 413),
])
def test_upload_validation_rejects_unsafe_files(client: TestClient, filename: str, mime: str, data: bytes, expected: int) -> None:
    response = client.post("/admin/media/upload", headers=headers(), files={"file": (filename, data, mime)})
    assert response.status_code == expected
    assert "Traceback" not in response.text


def test_unauthenticated_and_revoked_role_cannot_upload(client: TestClient, engine) -> None:
    assert client.post("/admin/media/upload", files={"file": ("chart.png", png_bytes(), "image/png")}).status_code == 403
    authenticated = headers()
    with engine.begin() as connection: connection.execute(text("UPDATE users SET role='USER' WHERE id=1"))
    assert client.post("/admin/media/upload", headers=authenticated, files={"file": ("chart.png", png_bytes(), "image/png")}).status_code == 403


def test_featured_attach_remove_trash_restore_and_safe_delete(client: TestClient, engine) -> None:
    media = upload(client).json(); media_id = media["id"]
    with engine.begin() as connection:
        content_id = connection.execute(text("INSERT INTO content_items (title,is_published) VALUES ('Published local post',TRUE) RETURNING id")).scalar_one()
    attached = client.post(f"/admin/content/{content_id}/featured-image", headers=headers(), json={"media_id": media_id})
    assert attached.status_code == 200 and attached.json()["public_url"] == media["public_url"]
    assert client.post(f"/admin/media/{media_id}/trash", headers=headers()).status_code == 200
    blocked = client.delete(f"/admin/media/{media_id}?confirmed=true", headers=headers())
    assert blocked.status_code == 409
    assert client.post(f"/admin/media/{media_id}/restore", headers=headers()).status_code == 200
    assert client.post(f"/admin/media/{media_id}/trash", headers=headers()).status_code == 200
    assert client.delete(f"/admin/content/{content_id}/featured-image", headers=headers()).status_code == 200
    assert client.delete(f"/admin/media/{media_id}?confirmed=true", headers=headers()).status_code == 200
    with engine.connect() as connection:
        assert connection.execute(text("SELECT image_url FROM content_items WHERE id=:id"), {"id": content_id}).scalar_one_or_none() is None
        events = set(connection.execute(text("SELECT event_type FROM admin_auth_audit_events")).scalars())
    assert {"CONTENT_FEATURED_IMAGE_SET", "CONTENT_FEATURED_IMAGE_REMOVED", "MEDIA_DELETED"}.issubset(events)
