"""Phase 2A CRUD and migration tests against isolated real PostgreSQL."""

from __future__ import annotations

from contextlib import contextmanager
from datetime import datetime, timedelta, timezone
import os
from pathlib import Path
from types import SimpleNamespace
from typing import Iterator

import bcrypt
from fastapi import FastAPI
from fastapi.testclient import TestClient
import pytest
from sqlalchemy import create_engine, text
from sqlalchemy.orm import Session, sessionmaker

from services import admin_auth_service, admin_content_service
from services.admin_content_api import router as content_router


ROOT = Path(__file__).resolve().parents[2]
DATABASE_URL = os.getenv("TEST_ADMIN_DATABASE_URL", "").strip()
pytestmark = pytest.mark.skipif(not DATABASE_URL, reason="isolated PostgreSQL is required")
PASSWORD = "Phase-2A-local-only-password!"
SETTINGS = SimpleNamespace(
    jwt_secret="phase-2a-isolated-jwt-secret-value-000000000000",
    jwt_issuer="phase-2a-local",
    admin_bff_shared_secret="phase-2a-bff-shared-secret-value-000000000000",
    admin_session_ttl_minutes=15,
    admin_login_window_seconds=900,
    admin_login_max_attempts=5,
)


@pytest.fixture(scope="module")
def engine():
    database_engine = create_engine(DATABASE_URL, pool_pre_ping=True)
    migration_014 = (ROOT / "migrations/014_admin_auth_foundation.sql").read_text()
    rollback_014 = (ROOT / "migrations/014_admin_auth_foundation.rollback.sql").read_text()
    migration_015 = (ROOT / "migrations/015_admin_content_cms.sql").read_text()
    rollback_015 = (ROOT / "migrations/015_admin_content_cms.rollback.sql").read_text()
    with database_engine.begin() as connection:
        connection.exec_driver_sql(
            """
            DO $$ BEGIN CREATE ROLE anon; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
            DO $$ BEGIN CREATE ROLE authenticated; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
            CREATE TABLE public.users (
                id BIGINT PRIMARY KEY, email TEXT NOT NULL UNIQUE, password_hash TEXT,
                role TEXT NOT NULL, email_verified BOOLEAN NOT NULL,
                approval_status TEXT NOT NULL, last_login_at TIMESTAMPTZ
            );
            CREATE TABLE public.content_categories (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                slug TEXT NOT NULL UNIQUE, title TEXT NOT NULL, description TEXT,
                icon TEXT, display_order INTEGER NOT NULL DEFAULT 0,
                is_public BOOLEAN NOT NULL DEFAULT TRUE,
                is_active BOOLEAN NOT NULL DEFAULT TRUE,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            CREATE TABLE public.content_items (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                category_id BIGINT REFERENCES public.content_categories(id) ON DELETE SET NULL,
                content_type TEXT NOT NULL, slug TEXT, subcategory TEXT,
                status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published')),
                title TEXT NOT NULL, excerpt TEXT, body TEXT, image_url TEXT,
                external_url TEXT, is_public BOOLEAN NOT NULL DEFAULT TRUE,
                is_published BOOLEAN NOT NULL DEFAULT FALSE, published_at TIMESTAMPTZ,
                created_by BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            CREATE UNIQUE INDEX content_items_slug_unique_idx ON public.content_items(slug) WHERE slug IS NOT NULL;
            CREATE TABLE public.content_seo (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                content_id BIGINT NOT NULL UNIQUE REFERENCES public.content_items(id) ON DELETE CASCADE,
                slug TEXT NOT NULL UNIQUE, meta_title TEXT, meta_description TEXT,
                focus_keyword TEXT, internal_links JSONB NOT NULL DEFAULT '[]',
                faq JSONB NOT NULL DEFAULT '[]', schema_jsonld JSONB NOT NULL DEFAULT '{}',
                open_graph JSONB NOT NULL DEFAULT '{}', twitter_card JSONB NOT NULL DEFAULT '{}',
                image_prompt TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            """
        )
        connection.exec_driver_sql(migration_014)
        connection.exec_driver_sql(migration_015)
        connection.exec_driver_sql(rollback_015)
        remaining = connection.execute(
            text(
                """
                SELECT COUNT(*) FROM information_schema.columns
                WHERE table_schema='public' AND table_name='content_items'
                  AND column_name IN ('scheduled_at','deleted_at','deleted_by')
                """
            )
        ).scalar_one()
        assert remaining == 0
        connection.exec_driver_sql(migration_015)
    yield database_engine
    with database_engine.begin() as connection:
        connection.exec_driver_sql(rollback_015)
        connection.exec_driver_sql(rollback_014)
        connection.exec_driver_sql(
            "DROP TABLE public.content_seo, public.content_items, public.content_categories, public.users"
        )
    database_engine.dispose()


@pytest.fixture(autouse=True)
def rows(engine, monkeypatch: pytest.MonkeyPatch):
    password_hash = bcrypt.hashpw(PASSWORD.encode(), bcrypt.gensalt()).decode()
    with engine.begin() as connection:
        connection.execute(text("TRUNCATE admin_auth_audit_events, admin_login_attempts, admin_sessions, content_seo, content_items, content_categories, users RESTART IDENTITY CASCADE"))
        connection.execute(text("INSERT INTO users (id,email,password_hash,role,email_verified,approval_status) VALUES (1,'admin@phase2a.invalid',:hash,'ADMIN',TRUE,'APPROVED'), (2,'user@phase2a.invalid',:hash,'USER',TRUE,'APPROVED')"), {"hash": password_hash})
        connection.execute(text("INSERT INTO content_categories (id,slug,title,description,display_order) VALUES (1,'research','Research','Local test category',10)"))
        connection.execute(
            text("SELECT setval(pg_get_serial_sequence('content_categories', 'id'), 1, true)")
        )
    factory = sessionmaker(bind=engine, class_=Session, expire_on_commit=False)

    @contextmanager
    def scope() -> Iterator[Session]:
        session = factory()
        try:
            yield session
            session.commit()
        except Exception:
            session.rollback()
            raise
        finally:
            session.close()

    monkeypatch.setattr(admin_content_service, "session_scope", scope)
    monkeypatch.setattr(admin_auth_service, "session_scope", scope)
    monkeypatch.setattr(admin_auth_service, "get_settings", lambda: SETTINGS)
    yield


def payload(title: str = "Gold market structure") -> dict[str, object]:
    return {
        "title": title, "slug": title.lower().replace(" ", "-"),
        "excerpt": "Synthetic local excerpt", "body": "Synthetic local body content.",
        "category_id": 1, "subcategory": "daily", "status": "draft",
        "scheduled_at": None, "published_at": None,
    }


def create(kind: str = "posts", **changes: object) -> dict[str, object]:
    values = {**payload(), **changes}
    return admin_content_service.save_admin_content(
        kind=kind, actor_id=1, request_id="create-test", **values
    )


def test_migration_columns_indexes_and_foreign_key(engine) -> None:
    with engine.connect() as connection:
        columns = set(connection.execute(text("SELECT column_name FROM information_schema.columns WHERE table_schema='public' AND table_name='content_items'")).scalars())
        indexes = set(connection.execute(text("SELECT indexname FROM pg_indexes WHERE schemaname='public' AND tablename='content_items'")).scalars())
        deleted_fk = connection.execute(text("SELECT COUNT(*) FROM pg_constraint WHERE contype='f' AND conrelid='content_items'::regclass AND pg_get_constraintdef(oid) LIKE '%deleted_by%'" )).scalar_one()
    assert {"scheduled_at", "deleted_at", "deleted_by"}.issubset(columns)
    assert {"content_items_admin_listing_idx", "content_items_scheduled_idx"}.issubset(indexes)
    assert deleted_fk == 1


def test_post_create_read_update_publish_unpublish_and_trash() -> None:
    post = create()
    assert post["status"] == "draft"
    updated = admin_content_service.save_admin_content(
        kind="posts", content_id=post["id"], actor_id=1, request_id="update-test",
        **payload("Updated gold outlook"),
    )
    assert updated["title"] == "Updated gold outlook"
    published = admin_content_service.transition_content(kind="posts", content_id=post["id"], actor_id=1, action="publish", request_id="publish")
    assert published["status"] == "published"
    unpublished = admin_content_service.transition_content(kind="posts", content_id=post["id"], actor_id=1, action="unpublish", request_id="unpublish")
    assert unpublished["status"] == "draft"
    trashed = admin_content_service.transition_content(kind="posts", content_id=post["id"], actor_id=1, action="trash", request_id="trash")
    assert trashed["status"] == "trash"
    listing = admin_content_service.list_admin_content(kind="posts", page=1, page_size=20, status="trash")
    assert listing["total"] == 1


def test_page_crud_publish_and_unpublish() -> None:
    page = create(kind="pages", title="About local staging", slug="about-local-staging")
    assert page["content_type"] == "PAGE"
    published = admin_content_service.transition_content(kind="pages", content_id=page["id"], actor_id=1, action="publish", request_id="publish-page")
    assert published["status"] == "published"
    assert admin_content_service.transition_content(kind="pages", content_id=page["id"], actor_id=1, action="unpublish", request_id="unpublish-page")["status"] == "draft"


def test_future_schedule_remains_draft() -> None:
    scheduled_at = datetime.now(timezone.utc) + timedelta(days=1)
    scheduled = create(
        title="Scheduled local post", slug="scheduled-local-post",
        status="published", scheduled_at=scheduled_at,
    )
    assert scheduled["status"] == "draft"
    assert scheduled["scheduled_at"] == scheduled_at


def test_duplicate_slug_is_rejected_across_content_and_seo(engine) -> None:
    first = create(slug="unique-slug")
    with pytest.raises(admin_content_service.DuplicateSlugError):
        create(title="Another title", slug="unique-slug")
    with engine.begin() as connection:
        connection.execute(text("INSERT INTO content_seo (content_id,slug) VALUES (:id,'seo-owned-slug')"), {"id": first["id"]})
    with pytest.raises(admin_content_service.DuplicateSlugError):
        create(title="Third title", slug="seo-owned-slug")


def test_pagination_search_status_filter_and_safe_sort() -> None:
    for number in range(5):
        create(title=f"Research post {number}", slug=f"research-post-{number}")
    page = admin_content_service.list_admin_content(kind="posts", page=2, page_size=2, search="Research", status="draft", sort="title_asc")
    assert page["total"] == 5 and len(page["items"]) == 2 and page["pages"] == 3
    safe = admin_content_service.list_admin_content(kind="posts", page=1, page_size=2, sort="DROP TABLE users")
    assert len(safe["items"]) == 2


def test_category_create_update_disable_and_duplicate() -> None:
    category = admin_content_service.save_admin_category(actor_id=1, title="Education", slug="education", description="Local", display_order=20, is_public=True, is_active=True, request_id="category-create")
    updated = admin_content_service.save_admin_category(category_id=category["id"], actor_id=1, title="Market Education", slug="education", description="Updated", display_order=21, is_public=True, is_active=True, request_id="category-update")
    assert updated["title"] == "Market Education"
    with pytest.raises(admin_content_service.DuplicateSlugError):
        admin_content_service.save_admin_category(actor_id=1, title="Duplicate", slug="education", description="", display_order=0, is_public=True, is_active=True, request_id="duplicate")
    assert not admin_content_service.disable_admin_category(category_id=category["id"], actor_id=1, request_id="disable")["is_active"]


def test_admin_api_authorization_csrf_boundary_and_audit_events(engine) -> None:
    app = FastAPI()
    app.include_router(content_router)
    client = TestClient(app)
    assert client.get("/admin/content/posts").status_code == 403
    admin = admin_auth_service.login_admin(email="admin@phase2a.invalid", password=PASSWORD, ip_address="192.0.2.1", user_agent="integration", request_id="login")
    headers = {"Authorization": f"Bearer {admin.token}", "X-Admin-BFF-Key": SETTINGS.admin_bff_shared_secret}
    created = client.post("/admin/content/posts", headers=headers, json=payload("API post"))
    assert created.status_code == 201
    assert client.get("/admin/content/posts", headers=headers).status_code == 200
    with engine.connect() as connection:
        events = set(connection.execute(text("SELECT event_type FROM admin_auth_audit_events")).scalars())
    assert {"LOGIN", "CONTENT_CREATED"}.issubset(events)
    with pytest.raises(admin_auth_service.AdminAccessForbidden):
        admin_auth_service.login_admin(email="user@phase2a.invalid", password=PASSWORD, ip_address="192.0.2.2", user_agent="integration", request_id="user-login")


def test_database_role_change_revokes_content_access(engine) -> None:
    app = FastAPI()
    app.include_router(content_router)
    client = TestClient(app)
    admin = admin_auth_service.login_admin(
        email="admin@phase2a.invalid", password=PASSWORD,
        ip_address="192.0.2.3", user_agent="integration",
        request_id="role-change-login",
    )
    with engine.begin() as connection:
        connection.execute(text("UPDATE users SET role = 'USER' WHERE id = 1"))
    response = client.get(
        "/admin/content/posts",
        headers={
            "Authorization": f"Bearer {admin.token}",
            "X-Admin-BFF-Key": SETTINGS.admin_bff_shared_secret,
        },
    )
    assert response.status_code == 403
