"""Phase 3B service tests against isolated real PostgreSQL."""
from __future__ import annotations

from contextlib import contextmanager
import os
from pathlib import Path
from typing import Iterator

import pytest
from sqlalchemy import create_engine, text
from sqlalchemy.orm import Session, sessionmaker

from services import admin_seo_service

ROOT = Path(__file__).resolve().parents[2]
DATABASE_URL = os.getenv("TEST_ADMIN_DATABASE_URL", "").strip()
pytestmark = pytest.mark.skipif(not DATABASE_URL, reason="isolated PostgreSQL is required")


@pytest.fixture(scope="module")
def engine():
    db = create_engine(DATABASE_URL, pool_pre_ping=True)
    auth = (ROOT / "migrations/014_admin_auth_foundation.sql").read_text()
    auth_rollback = (ROOT / "migrations/014_admin_auth_foundation.rollback.sql").read_text()
    content = (ROOT / "migrations/015_admin_content_cms.sql").read_text()
    content_rollback = (ROOT / "migrations/015_admin_content_cms.rollback.sql").read_text()
    media = (ROOT / "migrations/016_admin_media_library.sql").read_text()
    media_rollback = (ROOT / "migrations/016_admin_media_library.rollback.sql").read_text()
    seo = (ROOT / "migrations/017_admin_seo_management.sql").read_text()
    seo_rollback = (ROOT / "migrations/rollback/017_admin_seo_management.rollback.sql").read_text()
    with db.begin() as connection:
        connection.exec_driver_sql("""
        DO $$ BEGIN CREATE ROLE anon; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
        DO $$ BEGIN CREATE ROLE authenticated; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
        CREATE TABLE public.users (id BIGINT PRIMARY KEY,email TEXT UNIQUE,password_hash TEXT,role TEXT,email_verified BOOLEAN,approval_status TEXT,last_login_at TIMESTAMPTZ);
        CREATE TABLE public.content_categories (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,slug TEXT UNIQUE,title TEXT,description TEXT,icon TEXT,display_order INTEGER DEFAULT 0,is_public BOOLEAN DEFAULT TRUE,is_active BOOLEAN DEFAULT TRUE,created_at TIMESTAMPTZ DEFAULT NOW(),updated_at TIMESTAMPTZ DEFAULT NOW());
        CREATE TABLE public.content_items (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,category_id BIGINT REFERENCES public.content_categories(id),content_type TEXT NOT NULL,slug TEXT,subcategory TEXT,status TEXT DEFAULT 'draft',title TEXT NOT NULL,excerpt TEXT,body TEXT,image_url TEXT,external_url TEXT,is_public BOOLEAN DEFAULT TRUE,is_published BOOLEAN DEFAULT FALSE,published_at TIMESTAMPTZ,created_by BIGINT REFERENCES public.users(id),created_at TIMESTAMPTZ DEFAULT NOW(),updated_at TIMESTAMPTZ DEFAULT NOW());
        CREATE UNIQUE INDEX content_items_slug_unique_idx ON public.content_items(slug) WHERE slug IS NOT NULL;
        CREATE TABLE public.content_seo (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,content_id BIGINT NOT NULL UNIQUE REFERENCES public.content_items(id) ON DELETE CASCADE,slug TEXT NOT NULL UNIQUE,meta_title TEXT,meta_description TEXT,focus_keyword TEXT,internal_links JSONB NOT NULL DEFAULT '[]',faq JSONB NOT NULL DEFAULT '[]',schema_jsonld JSONB NOT NULL DEFAULT '{}',open_graph JSONB NOT NULL DEFAULT '{}',twitter_card JSONB NOT NULL DEFAULT '{}',image_prompt TEXT,audit_issues JSONB NOT NULL DEFAULT '[]',last_audited_at TIMESTAMPTZ,created_at TIMESTAMPTZ DEFAULT NOW(),updated_at TIMESTAMPTZ DEFAULT NOW());
        """)
        connection.exec_driver_sql(auth)
        connection.exec_driver_sql(content)
        connection.exec_driver_sql(media)
        connection.exec_driver_sql(seo)
        connection.exec_driver_sql(seo_rollback)
        assert connection.execute(text("SELECT COUNT(*) FROM information_schema.columns WHERE table_name='content_seo' AND column_name='seo_score'")).scalar_one() == 0
        connection.exec_driver_sql(seo)
    yield db
    with db.begin() as connection:
        connection.exec_driver_sql(seo_rollback)
        connection.exec_driver_sql(media_rollback)
        connection.exec_driver_sql(content_rollback)
        connection.exec_driver_sql(auth_rollback)
        connection.exec_driver_sql("DROP TABLE public.content_seo,public.content_items,public.content_categories,public.users")
    db.dispose()


@pytest.fixture(autouse=True)
def isolated(engine, monkeypatch: pytest.MonkeyPatch) -> Iterator[None]:
    factory = sessionmaker(bind=engine, expire_on_commit=False)
    body = "Gold market guide explains risk controls and position sizing. " + "Disciplined traders review evidence before every decision. " * 70
    with engine.begin() as connection:
        connection.execute(text("TRUNCATE admin_auth_audit_events,media_assets,content_seo,content_items,content_categories,users RESTART IDENTITY CASCADE"))
        connection.execute(text("INSERT INTO users(id,email,role,email_verified,approval_status) VALUES (1,'admin@phase3b.invalid','ADMIN',TRUE,'APPROVED')"))
        connection.execute(text("INSERT INTO content_categories(id,slug,title) VALUES (1,'research','Research')"))
        connection.execute(text("INSERT INTO media_assets(id,storage_provider,bucket,storage_path,public_url,original_filename,stored_filename,mime_type,size_bytes,width,height,alt_text,source_type,uploaded_by) VALUES (1,'LOCAL','admin-media','seo/image.png','http://local.invalid/image.png','image.png','image-unique.png','image/png',100,100,80,'Gold chart','MANUAL_UPLOAD',1)"))
        content_id = connection.execute(text("INSERT INTO content_items(category_id,content_type,slug,title,excerpt,body,image_url,is_public,is_published,published_at,created_by,media_id) VALUES (1,'BLOG','gold-market-guide','Gold Market Guide','A gold market guide for disciplined traders.',:body,'http://local.invalid/image.png',TRUE,TRUE,NOW(),1,1) RETURNING id"), {"body": body}).scalar_one()
        connection.execute(text("INSERT INTO content_seo(content_id,slug,internal_links) VALUES (:id,'gold-market-guide','[\"/learn\"]')"), {"id": content_id})

    @contextmanager
    def scope() -> Iterator[Session]:
        session = factory()
        try:
            yield session
            session.commit()
        except Exception:
            session.rollback()
            raise
        finally:
            session.close()
    monkeypatch.setattr(admin_seo_service, "session_scope", scope)
    monkeypatch.setenv("SEO_APPROVED_ORIGINS", "https://example.test")
    yield


def payload() -> dict:
    return {"meta_title": "Gold Market Guide for Disciplined Traders", "meta_description": "Learn a practical gold market process with risk controls, repeatable analysis, and clear decision points for disciplined traders every day.", "focus_keyword": "gold market guide", "secondary_keywords": ["risk control", "gold trading"], "canonical_url": "https://example.test/gold-market-guide", "robots_index": True, "robots_follow": True, "sitemap_included": True, "open_graph": {"title": "Gold Market Guide", "description": "Practical gold education", "media_id": 1}, "twitter_card": {"title": "Gold Market Guide", "description": "Practical gold education", "media_id": 1, "card_type": "summary_large_image"}, "faq": [{"question": "What is this guide?", "answer": "A disciplined market process."}], "schema_jsonld": {"@type": "Article", "headline": "Gold Market Guide"}}


def test_write_validate_score_list_summary_and_audit(engine) -> None:
    saved = admin_seo_service.save_admin_seo(content_id=1, actor_id=1, request_id="save", payload=payload())
    assert saved["canonical_url"] == "https://example.test/gold-market-guide"
    assert 0 <= saved["seo_score"] <= 100
    validated = admin_seo_service.validate_admin_seo(1, payload())
    assert validated["score"] == saved["seo_score"]
    scored = admin_seo_service.score_admin_seo(content_id=1, actor_id=1, request_id="score")
    assert scored["score"] == saved["seo_score"]
    assert admin_seo_service.list_admin_seo_issues(page=1, page_size=10)["total"] == 1
    assert admin_seo_service.get_admin_seo_summary()["total"] == 1
    with engine.connect() as connection:
        events = set(connection.execute(text("SELECT event_type FROM admin_auth_audit_events")).scalars())
    assert {"CONTENT_SEO_UPDATED", "CONTENT_SEO_SCORED"}.issubset(events)


@pytest.mark.parametrize("field,value", [
    ("canonical_url", "javascript:alert(1)"),
    ("canonical_url", "https://unapproved.invalid/path"),
    ("faq", [{"question": "Unsafe?", "answer": "<script>alert(1)</script>"}]),
    ("schema_jsonld", {"@type": "ExecutableThing"}),
])
def test_unsafe_values_are_rejected(field: str, value) -> None:
    candidate = payload(); candidate[field] = value
    with pytest.raises(ValueError):
        admin_seo_service.save_admin_seo(content_id=1, actor_id=1, request_id="unsafe", payload=candidate)
