"use client";

import Link from "next/link";
import { useState } from "react";
import type { Category } from "@/lib/content-api";
import type { SeoIssueItem, SeoSummary } from "@/lib/seo-api";

export function SeoDashboard({ data, summary, categories, filters, publicWebsiteUrl }: { data: { items: SeoIssueItem[]; page: number; pages: number; total: number }; summary: SeoSummary; categories: Category[]; filters: Record<string, string>; publicWebsiteUrl?: string }) {
  return <>
    <header className="studio-heading"><div><span className="eyebrow">Content optimization</span><h1>SEO Management</h1><p>Deterministic validation and transparent scoring for posts and pages.</p></div></header>
    <section className="studio-kpis seo-kpis" aria-label="SEO summary"><Kpi label="Content" value={summary.total} /><Kpi label="Average score" value={summary.average_score} /><Kpi label="Below 60" value={summary.low_score} /><Kpi label="Missing titles" value={summary.missing_title} /><Kpi label="Missing descriptions" value={summary.missing_description} /><Kpi label="Noindex" value={summary.noindex} /></section>
    <section className="content-panel"><form className="filter-bar studio-filters" action="/admin/seo"><select name="content_type" defaultValue={filters.content_type}><option value="all">All content</option><option value="posts">Posts</option><option value="pages">Pages</option></select><select name="status" defaultValue={filters.status}><option value="all">All statuses</option><option value="published">Published</option><option value="draft">Draft</option></select><select name="issue_type" defaultValue={filters.issue_type}><option value="all">All issues</option><option value="missing_seo_title">Missing SEO title</option><option value="missing_meta_description">Missing description</option><option value="canonical_valid">Invalid canonical</option><option value="featured_image_missing">Missing featured image</option><option value="image_alt_missing">Missing alt text</option><option value="schema_invalid">Invalid schema</option><option value="faq_invalid">Invalid FAQ</option><option value="noindex_content">Noindex</option><option value="indexing_sitemap_inconsistent">Sitemap inconsistency</option><option value="duplicate_seo_title">Duplicate SEO title</option><option value="duplicate_meta_description">Duplicate description</option></select><select name="category_id" defaultValue={filters.category_id}><option value="">All categories</option>{categories.map(category => <option value={category.id} key={category.id}>{category.title}</option>)}</select><label className="score-filter">Score <input type="number" name="min_score" min="0" max="100" defaultValue={filters.min_score} />–<input type="number" name="max_score" min="0" max="100" defaultValue={filters.max_score} /></label><button className="primary-button">Filter</button></form>
      <div className="seo-issue-list">{data.items.length ? data.items.map(item => <SeoRow key={item.id} item={item} publicWebsiteUrl={publicWebsiteUrl} />) : <div className="empty-table"><h2>No matching SEO records</h2><p>Adjust the filters or validate content from its editor.</p></div>}</div>
      <div className="pagination"><span>{data.total} records · Page {data.page} of {data.pages}</span><div>{data.page > 1 ? <Link href={pageHref(filters, data.page - 1)}>Previous</Link> : <span aria-disabled="true">Previous</span>}{data.page < data.pages ? <Link href={pageHref(filters, data.page + 1)}>Next</Link> : <span aria-disabled="true">Next</span>}</div></div>
    </section>
  </>;
}
function Kpi({ label, value }: { label: string; value: number }) { return <article className="studio-kpi"><div><small>{label}</small><strong>{value}</strong></div></article>; }
function SeoRow({ item, publicWebsiteUrl }: { item: SeoIssueItem; publicWebsiteUrl?: string }) { const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const kind = item.content_type === "PAGE" ? "pages" : "posts"; async function validate() { setBusy(true); setMessage(""); try { const csrfResponse = await fetch("/api/admin/auth/csrf", { cache: "no-store" }); const { csrfToken } = await csrfResponse.json() as { csrfToken: string }; const response = await fetch(`/api/admin/seo/${item.id}/score`, { method: "POST", headers: { "X-CSRF-Token": csrfToken } }); setMessage(response.ok ? "Validation stored." : "Validation failed."); } catch { setMessage("Validation failed."); } finally { setBusy(false); } } return <article className="seo-issue-row"><div className={`seo-score ${item.seo_score >= 80 ? "good" : item.seo_score >= 60 ? "fair" : ""}`}>{item.seo_score}</div><div className="seo-issue-content"><div><span className={`status-badge ${item.status}`}><i />{item.status}</span><small>{item.category || "Uncategorized"}</small></div><Link href={`/admin/${kind}/${item.id}/edit`}>{item.title}</Link><ul>{item.issues.slice(0, 4).map((issue, index) => <li key={`${issue.code}-${index}`}>{issue.message}</li>)}</ul></div><div className="seo-row-actions"><Link href={`/admin/${kind}/${item.id}/edit`}>Edit content</Link><button type="button" onClick={validate} disabled={busy}>{busy ? "Validating…" : "Run validation"}</button>{publicWebsiteUrl && item.status === "published" && <a href={`${publicWebsiteUrl}/${kind === "posts" ? "blog" : "page"}/${item.slug}`} target="_blank" rel="noreferrer">Public preview ↗</a>}{message && <small>{message}</small>}</div></article>; }
function pageHref(filters: Record<string, string>, page: number) { const query = new URLSearchParams(filters); query.set("page", String(page)); return `/admin/seo?${query}`; }
