import type { Metadata } from "next";
import Link from "next/link";
import { AutomationEnquiryForm } from "@/components/automation-enquiry-form";
import { Icon } from "@/components/icon";
import { siteUrl } from "@/lib/api";

export const metadata: Metadata = { title: "AI Automation Services for Global Businesses", description: "Secure, human-approved AI agents, n8n workflows and business automation built around real operational needs.", alternates: { canonical: "/automation-services" }, openGraph: { title: "VenusRealm Automation Services", description: "Secure automation systems for worldwide businesses.", url: "/automation-services", type: "website" } };

const services = [
  ["AI Agents","Turn repetitive research and coordination into an approval-aware assistant.","Scoped agent workflows, tools and review gates.","Operations, research and knowledge teams."],
  ["WhatsApp Automation","Reduce manual handling of approved business conversations.","Official-integration-ready workflow design and routing.","Enquiries, reminders and service updates."],
  ["Telegram Automation","Structure alerts, commands and community operations.","Bots, permissions, audit trails and human approval.","Research desks, communities and internal teams."],
  ["Email Automation","Move routine inbox work into reliable workflows.","Classification, drafting, routing and escalation rules.","Support, sales operations and administration."],
  ["CRM and Lead Automation","Keep qualified opportunities moving without spreadsheet drift.","Capture, enrichment, assignment and lifecycle workflows.","Sales teams, agencies and consultants."],
  ["Calendar and Booking Automation","Reduce scheduling friction and missed handoffs.","Availability, booking, reminders and operational follow-up.","Clinics, consultants and local services."],
  ["Customer Support Automation","Give teams faster context while preserving escalation paths.","Knowledge retrieval, triage and human handover.","E-commerce, SaaS and service businesses."],
  ["n8n Workflow Development","Connect fragmented systems with observable workflows.","Self-hosted or cloud-ready n8n design, tests and documentation.","Multi-system operations and internal tooling."],
  ["Business Dashboards","Turn operational data into decisions without fake analytics.","Role-aware dashboards backed by validated data.","Leadership, operations and delivery teams."],
  ["Custom API Integrations","Connect systems that do not work together out of the box.","Secure REST integrations, validation and failure handling.","Legacy tools, partner APIs and data platforms."],
  ["Website and Backend Automation","Build reliable workflows behind public and internal products.","Next.js, FastAPI, PostgreSQL and task automation.","Portals, content operations and bespoke platforms."],
  ["Social Publishing Workflows","Prepare approved content for consistent distribution.","Draft, review and publish-ready workflow foundations.","Editorial teams and brand operations."]
];
const useCases = ["E-commerce","Real estate","Healthcare administration","Coaches and consultants","Financial research businesses","Local service businesses","Agencies","Education","SaaS","Internal operations"];
const process = ["Discovery","Workflow mapping","Secure build","Testing and approval","Deployment","Support and optimization"];
const technology = ["AI APIs","n8n","Telegram","Official WhatsApp-compatible integrations","Gmail","Google Calendar","CRM systems","REST APIs","PostgreSQL","FastAPI","Next.js","Docker","Cloud deployment"];
const faqs = [["Which businesses do you work with?","Projects are evaluated by workflow fit, risk and operational value rather than geography or company size."],["Can existing tools be connected?","Often, yes. We first verify that each tool offers a safe supported API or integration path."],["Do you support WhatsApp and Telegram?","Yes, where official and policy-compliant integrations are available. External messages remain approval-aware."],["Is n8n required?","No. The architecture is selected for the project; n8n is one option, not a requirement."],["Can the system run on our server?","Self-hosted and customer-cloud options can be assessed during discovery."],["How is data protected?","Secrets stay server-side, access is scoped, and staging and audit controls are designed into the workflow."],["How long does a project take?","Timing depends on integrations, approvals and testing. A discovery review produces a realistic plan."],["Is ongoing support available?","Ongoing monitoring, maintenance and workflow optimization can be included in a tailored proposal."]];

export default function AutomationServicesPage() {
  const schema = { "@context":"https://schema.org", "@type":"Service", name:"Business Automation Services", provider:{"@type":"Organization",name:"VenusRealm",url:siteUrl()}, areaServed:"Worldwide", serviceType:"AI and business workflow automation", url:siteUrl("/automation-services") };
  const breadcrumb = { "@context":"https://schema.org", "@type":"BreadcrumbList", itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:siteUrl()},{"@type":"ListItem",position:2,name:"Automation Services",item:siteUrl("/automation-services")}] };
  return <article className="automation-page"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumb)}}/>
    <nav className="breadcrumb" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><span>Automation Services</span></nav>
    <header className="automation-hero"><div><span className="eyebrow"><span/>GLOBAL AUTOMATION DELIVERY</span><h1>Automation systems built for real business operations.</h1><p>VenusRealm designs secure AI assistants, integrations and approval-aware workflows for businesses worldwide—without inflated claims or unnecessary complexity.</p><div className="hero-actions"><a className="button button-gold" href="#project-enquiry">Start Your Automation Project</a><a className="button button-ghost" href="#services">Explore Services</a></div><div className="trust-chips"><span><Icon name="check" size={15}/>Human-approved workflows</span><span><Icon name="shield" size={15}/>Secure integrations</span><span><Icon name="target" size={15}/>Built for real operations</span></div></div><aside><Icon name="brain" size={48}/><strong>Map. Build. Approve.</strong><p>Every engagement starts with the workflow, the risks and the people responsible for the outcome.</p></aside></header>
    <section id="services"><div className="section-heading"><div><span className="eyebrow">SERVICES</span><h2>Practical automation across the customer and operations lifecycle.</h2></div><p>Each service is scoped around a measurable operational problem and an explicit approval model.</p></div><div className="automation-service-grid">{services.map(([title,problem,delivery,examples])=><article key={title}><span className="service-index">{String(services.findIndex(x=>x[0]===title)+1).padStart(2,"0")}</span><h3>{title}</h3><p><b>Problem solved:</b> {problem}</p><p><b>Deliverable:</b> {delivery}</p><small>{examples}</small><a href="#project-enquiry">Enquire about this service →</a></article>)}</div></section>
    <section className="automation-band"><div><span className="eyebrow">BUSINESS USE CASES</span><h2>Designed around the way your team actually works.</h2></div><div className="use-case-grid">{useCases.map(item=><span key={item}><Icon name="check" size={16}/>{item}</span>)}</div></section>
    <section><div className="section-heading"><div><span className="eyebrow">DELIVERY PROCESS</span><h2>A clear path from operational problem to supported system.</h2></div></div><ol className="automation-process">{process.map((item,index)=><li key={item}><span>{String(index+1).padStart(2,"0")}</span><h3>{item}</h3><p>{["Clarify goals, constraints, owners and acceptable risk.","Document systems, data, exceptions and approval points.","Implement least-privilege integrations in a test environment.","Exercise normal, failure and recovery paths with stakeholders.","Release through a documented, reversible handover.","Monitor outcomes and improve the workflow as operations change."][index]}</p></li>)}</ol></section>
    <section className="technology-section"><div><span className="eyebrow">TECHNOLOGY</span><h2>Modern tools, selected only when they fit.</h2><p>Capability does not imply an existing connection. Every provider and permission is confirmed during discovery.</p></div><div>{technology.map(item=><span key={item}>{item}</span>)}</div></section>
    <section className="security-section"><div><Icon name="shield" size={42}/><span className="eyebrow">SECURITY AND APPROVAL</span><h2>Controls are part of the workflow—not an afterthought.</h2></div><ul><li>Secrets remain in server-side environments.</li><li>Role-based access limits operational actions.</li><li>Audit events create a reviewable history.</li><li>External or destructive actions can require human approval.</li><li>Testing and staging environments protect live operations.</li><li>Privacy-conscious data minimization guides implementation.</li></ul></section>
    <section><div className="section-heading"><div><span className="eyebrow">PROJECT TYPES</span><h2>Start at the right level of scope.</h2></div><p>Pricing follows discovery and delivery risk. Request a quote for a factual estimate.</p></div><div className="project-type-grid">{["Small workflow","Multi-system automation","AI assistant","Custom automation platform","Ongoing optimization"].map(item=><article key={item}><h3>{item}</h3><p>A scoped engagement with documented outcomes, responsibilities and approval points.</p><a href="#project-enquiry">Request a quote →</a></article>)}</div></section>
    <section className="faq-section"><div className="section-heading centered-heading"><div><span className="eyebrow">FAQ</span><h2>Questions before discovery.</h2></div></div><div className="faq-list">{faqs.map(([question,answer])=><details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></section>
    <section id="project-enquiry" className="enquiry-section"><div><span className="eyebrow">START A PROJECT</span><h2>Tell us where work is slowing your business down.</h2><p>Share enough context for a useful first review. Submission does not trigger automatic messages or create a contractual commitment.</p><ul><li>No file uploads</li><li>No credentials or confidential customer data</li><li>Human review before contact</li></ul></div><AutomationEnquiryForm/></section>
    <section className="final-cta"><div><span className="eyebrow">BUILD WITH CLARITY</span><h2>Start with the workflow your team needs most.</h2></div><div className="cta-actions"><a className="button button-gold" href="#project-enquiry">Start Your Automation Project</a><Link className="button button-ghost" href="/contact">Contact VenusRealm</Link></div></section>
  </article>;
}
