import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";

const policies = {
  "risk-disclaimer": { title: "Risk Disclaimer", intro: "Important limitations for all VenusRealm market content.", sections: [["Educational information only","VenusRealm content, including signals and astrology material, is general education and not investment, legal or tax advice."],["Market risk","Gold, foreign exchange, cryptoassets and leveraged instruments can move rapidly. You may lose some or all capital committed to a position."],["No guarantee","No analysis, model, signal or past result guarantees a future outcome. Verify information independently and seek qualified advice where appropriate."]] },
  "privacy-policy": { title: "Privacy Policy", intro: "How this public preview handles visitor information.", sections: [["Public browsing","The public website does not ask for account credentials. Login and recovery continue through the separate protected authentication service."],["Infrastructure data","Hosting providers may process routine request information such as IP address, browser details and timestamps for security and reliability."],["Contact channels","External social and messaging destinations have their own privacy practices. They appear only when configured by the site operator."]] },
  "terms": { title: "Terms and Conditions", intro: "Conditions for using VenusRealm public research.", sections: [["Acceptable use","Use the site lawfully and do not attempt to disrupt, scrape abusively or gain unauthorized access to protected systems."],["Research limitations","Content may be delayed, incomplete or inaccurate. You are responsible for decisions made after reading it."],["Availability","Pages, channels and features may change or become unavailable without notice during preview operation."]] },
  "cookie-policy": { title: "Cookie Policy", intro: "A concise statement for the current public preview.", sections: [["Current public experience","The public content experience does not require advertising or analytics cookies in this phase."],["Protected services","The separate authentication service may use essential cookies for security and session management."],["Future changes","If non-essential cookies are introduced, this policy and any required controls should be updated before activation."]] },
  "refund-policy": { title: "Refund Policy", intro: "Current commercial status of the public preview.", sections: [["No public checkout","This preview does not provide a public payment or subscription checkout and does not collect payment information."],["No invented promise","Because no paid public-web product is offered here, no synthetic refund workflow is displayed."],["Future paid services","Any future paid offer should publish product-specific pricing, cancellation and refund terms before accepting payment."]] }
} as const;

type PolicySlug = keyof typeof policies;
export function generateStaticParams() { return Object.keys(policies).map((slug) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const policy = policies[(await params).slug as PolicySlug]; return { title: policy?.title || "Policy" }; }
export default async function LegalPage({ params }: { params: Promise<{ slug: string }> }) { const slug = (await params).slug as PolicySlug; const policy = policies[slug]; if (!policy) notFound(); return <article className="content-page"><nav className="breadcrumb" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><span>Legal</span></nav><header className="content-page-header"><span className="eyebrow">LEGAL</span><h1>{policy.title}</h1><p>{policy.intro}</p></header><div className="article-body">{policy.sections.map(([title, body]) => <section key={title}><h2>{title}</h2><p>{body}</p></section>)}</div></article>; }
